nuxt/docs

en/guide/commands.md
`has to be ran before` doesn't really make any sense, corrected typo.
=> Corrected Typo

en/guide/assets.md
We use amount of with uncountable nouns. Number of is used with countable nouns
=> Fix grammar.

en/guide/vuex-store.md
Example issues: 
- https://github.com/nuxt/nuxt.js/issues/169#issuecomment-275759867
- https://github.com/nuxt/nuxt.js/issues/175
=> Mention that only store/index.js receives the nuxtServerInit action

en/guide/routing.md
I have corrected the description of the dynamic routes. Please check it out.
=> Correct the description of Dynamic Routes

en/examples/auth-routes.md
=> adds async note for `nuxtServerInit`

cn/faq/google-analytics.md, cn/faq/host-port.md, en/faq/google-analytics.md, en/faq/host-port.md
I have formatted faq pages.
* Format indent of code ( indent 2 )
* Make page title `h1`
=> Format FAQ pages

en/examples/auth-routes.md, ru/examples/auth-routes.md
I have fixed typos. Please check it out.
=> Fix typos in auth routes example

en/api/configuration-build.md
Fix typo in configuration-build.md
https://nuxtjs.org/api/configuration-build/#loaders
=> Fix typo in configuration-build.md

en/faq/duplicated-meta-tags.md, en/guide/routing.md
I have fixed dead links. Please check it out.
=> Fix dead links

en/api/index.md
Minor adjective clue for context newbies (like me)
=> Minor clarification

en/guide/async-data.md
Very minor grammar and copy edits to improve legibility.
=> Some grammar and copy edits.

README.md
I have reflected the update of Japanese translation repository name.
=> Reflect the update of Japanese translation repository name

en/guide/views.md
=> add missing / to nuxt component

en/faq/dokku-deployment.md
I'm tried deploy nuxt.js to Dokku , it's a little different with Heroku .
So, I write a doc . ( copy from heroku-deployment.md )
hope it useful for someone .
Sorry , I have some mistake with my fork repo .
=> add dokku deployment ( FAQ ) modify from Heroku

jp/guide/menu.json, jp/guide/views.md
I have reflected the commit pushed to master directly "update views documentation · nuxt/docs@df25b58" to Japanese translation.
=> Reflect "update views documentation · nuxt/docs@df25b58" to Japanese translation

jp/guide/directory-structure.md
I have reflected "update middleware alias · nuxt/docs@be36811" to Japanese translation.
=> Reflect "update middleware alias · nuxt/docs@be36811" to Japanese translation

jp/api/pages-layout.md, jp/guide/routing.md
I have reflected "add layout as function · nuxt/docs@2bfb234" to Japanese translation.
=> Reflect "add layout as function · nuxt/docs@2bfb234" to Japanese translation

en/guide/routing.md
To match [this example](https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components).
=> Update transition example to match Vue one

jp/api/pages-validate.md
I have reflected "update doc validate Method" #71 to Japanese translation.
=> Reflect "update doc validate Method" #71 to Japanese translation

jp/faq/google-analytics.md
I have reflected "Disable Eslint for the Google Analytics snippet" #72 to Japanese translation.
=> Reflect "Disable Eslint for the Google Analytics snippet" #72 to Japanese translation

en/faq/dokku-deployment.md, jp/faq/dokku-deployment.md, jp/faq/heroku-deployment.md, jp/faq/menu.json
I have reflected "add dokku deployment ( FAQ ) modify from Heroku" #79 to Japanese translation.
=> Reflect "add dokku deployment ( FAQ ) modify from Heroku" #79 to Japanese translation

ja/api/configuration-build.md
I have reflected "Add manifest file · nuxt/docs@bf086fb" to Japanese translation.
=> Reflect "Add manifest file · nuxt/docs@bf086fb" to Japanese translation

ja/guide/routing.md
I have reflected "Update transition example to match Vue one" #82 to Japanese translation.
=> Reflect "Update transition example to match Vue one" #82 to Japanese translation

en/guide/vuex-store.md
=> Fix small typo

en/guide/routing.md
Just a small typo in the user guide
=> Wrote "happen" as "append" in dynamic nested route

en/api/configuration-router.md
Update docs due to https://github.com/nuxt/nuxt.js/pull/691
=> add linkExactActiveClass documented

ja/api/components-nuxt-link.md
original is https://github.com/nuxt/docs/blob/master/en/api/components-nuxt-link.md
cc:/ @inouetakuya
=> Fix Japanese format the same as English

en/api/configuration-build.md, en/api/configuration-dev.md, en/api/configuration-env.md, en/api/configuration-plugins.md
=> Beautify markdown in accordance with GitHub flavor

package.json
ref: https://docs.npmjs.com/files/package.json#engines
=> How about to specify node engine in package.json?

ja/api/configuration-router.md
=> Fix typo of Japanese

zh/guide/async-data.md
copy code from https://github.com/nuxt/docs/edit/master/en/guide/async-data.md
=> [fix] zh async-data example code error

en/examples/auth-routes.md, en/guide/vuex-store.md, ja/examples/auth-routes.md, ja/guide/vuex-store.md, ko/examples/auth-routes.md, ko/guide/vuex-store.md, ru/examples/auth-routes.md, ru/examples/vuex-store.md, ru/guide/vuex-store.md, zh/examples/auth-routes.md, zh/guide/vuex-store.md
So that others don't stumble across this as well, helps out [#754](https://github.com/nuxt/nuxt.js/issues/754) and fixes [#787](https://github.com/nuxt/nuxt.js/issues/787)
=> Update store examples to reflect v1 changes

en/guide/vuex-store.md
=> Grammar fix on vuex-store.md

en/guide/vuex-store.md
mutations and actions should be objects in module mode, not functions
=> Fixed error in vuex-store.md

en/guide/index.md
Added missing word to a sentence in "Static Generated" section.
=> Added missing word

en/api/index.md, en/guide/async-data.md
I'm pretty sure this is what was meant.
=> fix typo in asyncData alert

en/guide/routing.md
Just a few minor grammatical corrections.
=> Grammar fixes in the Middleware section

en/faq/host-port.md
The [cross-env](https://www.npmjs.com/package/cross-env) package is great for use in `package.json` scripts for better cross platform development.
=> Suggest use cross-env package

en/api/configuration-build.md
=> Fix typo in configuration/build 

en/guide/vuex-store.md
Correct docs as mentioned in #757
=> [typo] fix docs on vuex-store.md

en/api/configuration-build.md, en/api/configuration-cache.md, en/api/configuration-css.md, en/api/configuration-transition.md, en/api/nuxt.md, en/guide/configuration.md, en/guide/directory-structure.md, en/guide/installation.md, en/guide/menu.json, en/guide/plugins.md, en/guide/routing.md
I have taken the liberty of updating the grammar and wording on the first three sections of your documentation: `Installation`, `Directory Structure` and `Configuration`. 
I figured I would stop here before continuing to get a feel as to whether or not you would like me to proceed any further. I personally feel Nuxt.js stands to gain quite tremendously from a bit of a language update in the english documentation and I am more than willing to assist if needed. 
Great job so far on Nuxt by the way 💯 .
=> [WIP] English Language Adjustments

en/examples/auth-routes.md, es/examples/auth-routes.md, fr/examples/auth-routes.md, ja/examples/auth-routes.md, ko/examples/auth-routes.md, ru/examples/auth-routes.md, zh/examples/auth-routes.md
Related to issue https://github.com/nuxt/nuxt.js/issues/1608
=> Fix outdated example

fr/guide/installation.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/fr/review/244)
=> Relecture du fichier d'installation

en/guide/directory-structure.md
=> [Doc EN]: `guide/directory-structure.md` review

en/guide/installation.md
=> [Doc EN]: `guide/installation.md` review

en/guide/index.md
=> [Doc EN]: `guide/index.md` review

en/guide/views.md
=> [Doc EN]: `guide/views.md` review 

en/guide/directory-structure.md, en/guide/views.md
=> [Doc EN]: Consistency changes

en/guide/vuex-store.md
=> [Doc EN]: `vuex-store.md` review.

zh/guide/commands.md
correct the translation of 'how',from '如果' to '如何'
=> correct the translation of 'how',from '如果' to '如何'

en/guide/routing.md
=> Better description for Guide/Routing

en/guide/commands.md
=> [Doc EN]: `commands.md` review.

fr/api/internals-module-container.md, fr/faq/menu.json, fr/faq/nginx-proxy.md, fr/guide/menu.json, fr/guide/modules.md
Hi @Atinux !
The last file for a  full French Guide Translated!
=> [Doc FR]: `modules.md` translation + `nginx-proxy.md` with translation message

fr/examples/async-data.md, fr/examples/auth-routes.md, fr/examples/cached-components.md, fr/examples/custom-loading.md, fr/examples/custom-routes.md, fr/examples/global-css.md, fr/examples/hello-world.md, fr/examples/i18n.md, fr/examples/layouts.md, fr/examples/menu.json, fr/examples/middleware.md, fr/examples/nested-routes.md, fr/examples/plugins.md, fr/examples/routes-transitions.md, fr/examples/seo-html-head.md, fr/examples/testing.md, fr/examples/vuex-store.md
Hi @Atinux!
The french part for examples pages.
=> [Doc FR]: All examples set in French

en/examples/auth-routes.md, en/examples/menu.json, en/examples/plugins.md
=> [Docs EN]: Examples directory reviews

en/guide/plugins.md
Example used: https://github.com/nuxt/nuxt.js/blob/b48b2c5e6d0834b7f760ec5abd7a8170da9a1f7c/examples/with-cookies/plugins/cookies.js#L15-L19
=> Update plugins documentation to include inject

ja/guide/assets.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/258)
=> Add HTML comments to ja/guide/assets.md

ja/guide/plugins.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/259)
=> Translate the inject function in ja/guide/plugins.md

en/faq/async-data-components.md, en/faq/css-flash.md, en/faq/dokku-deployment.md, en/faq/duplicated-meta-tags.md, en/faq/extend-webpack.md, en/faq/github-pages.md, en/faq/google-analytics.md, en/faq/heroku-deployment.md, en/faq/host-port.md, en/faq/jsx.md, en/faq/menu.json, en/faq/nginx-proxy.md, en/faq/now-deployment.md, en/faq/postcss-plugins.md, en/faq/pre-processors.md, en/faq/surge-deployment.md, en/faq/webpack-plugins.md, en/faq/window-document-undefined.md, en/guide/plugins.md
Hi @Atinux.
A provide some littles changes for consistency across documentation on last modifications.
+ Add constitency across all FAQ part.
=> [Doc EN]: `faq/* review`

fr/faq/async-data-components.md, fr/faq/css-flash.md, fr/faq/dokku-deployment.md, fr/faq/duplicated-meta-tags.md, fr/faq/extend-webpack.md, fr/faq/external-resources.md, fr/faq/github-pages.md, fr/faq/google-analytics.md, fr/faq/heroku-deployment.md, fr/faq/host-port.md, fr/faq/jsx.md, fr/faq/menu.json, fr/faq/nginx-proxy.md, fr/faq/now-deployment.md, fr/faq/postcss-plugins.md, fr/faq/pre-processors.md, fr/faq/surge-deployment.md, fr/faq/webpack-plugins.md, fr/faq/window-document-undefined.md, fr/guide/plugins.md
Hi @Atinux!
The french part for FAQ pages!
=> [Doc FR]: `faq/*` review.

en/lang.json
=> Bump to rc11

README.md
Old repository is not relevant anymore @Atinux.
That PR following the @rspt proposition here : https://github.com/nuxt/docs/issues/294 (I let @rspt check if all is correct for him).
=> [Doc FR]: Credits for French translation

en/api/index.md, en/api/pages-fetch.md, en/api/pages-head.md, en/api/pages-layout.md, en/api/pages-middleware.md, en/api/pages-scrolltotop.md, en/api/pages-transition.md, en/api/pages-validate.md
Hi @Atinux. This is the « Pages » section of the API reviewed
=> [Doc EN]: Review of Pages part of API

fr/api/menu.json, fr/api/pages-fetch.md, fr/api/pages-head.md, fr/api/pages-layout.md, fr/api/pages-middleware.md, fr/api/pages-scrolltotop.md, fr/api/pages-transition.md, fr/api/pages-validate.md
Hi @Atinux,
All pages for Pages part of API are now in french.
=> [Doc FR]: `api/page-*` reviews

fr/api/components-nuxt-child.md, fr/api/components-nuxt-link.md, fr/api/components-nuxt.md, fr/api/menu.json
Hi @Atinux 
New set of API translations!
=> [Doc FR]: `api/component-*` translations

en/guide/assets.md, en/guide/async-data.md, en/guide/commands.md, en/guide/configuration.md, en/guide/index.md, en/guide/plugins.md, en/guide/routing.md
Hi all,
I've created a PR to fix some punctuation. I've also reworded some sentences.
Thanks!
=> Fix some grammar and punctuation for clarity

en/faq/nginx-proxy.md
=> added Laravel Forge nginx configuration - fixes #303

README.md
I have removed original text. If it is not good, please correct me. Thanks in advance.
cc:/ @gbezyuk
=> Update translation section on README

ja/guide/vuex-store.md
fix plugin sample.
https://github.com/nuxt/docs/blob/master/en/guide/vuex-store.md#plugins
=> [DOC Ja] update vuex-store.md

en/api/nuxt-render-and-get-window.md, en/api/nuxt-render-route.md, en/api/nuxt-render.md, en/api/nuxt.md
Hi @Atinux,
Our last reviews :)
=> [Doc EN]: `api/nuxt-*.md` reviews

en/faq/menu.json
=> Update menu.json to add cached components

en/api/components-nuxt-link.md, en/faq/nginx-proxy.md, fr/api/components-nuxt-child.md, fr/api/components-nuxt-link.md, fr/api/components-nuxt.md, fr/api/configuration-build.md, fr/api/configuration-modules.md, fr/api/menu.json, fr/api/nuxt-render-and-get-window.md, fr/api/nuxt-render-route.md, fr/api/nuxt-render.md, fr/api/nuxt.md, fr/faq/cached-components.md, fr/faq/google-analytics.md, fr/faq/jsx.md, fr/faq/menu.json, fr/faq/nginx-proxy.md, fr/guide/assets.md, fr/guide/async-data.md, fr/guide/commands.md, fr/guide/configuration.md, fr/guide/index.md, fr/guide/plugins.md
Hi @Atinux !
I would only push the three new files but I implement a lot of modification since we have started translation to be up-to-date right now ;)
=> [Doc FR]: `api/nuxt-*.md` review + last change from EN update + small typo in EN doc

en/faq/cached-components.md, fr/api/nuxt-render-and-get-window.md, fr/api/nuxt-render-route.md, fr/api/nuxt-render.md, fr/faq/cached-components.md, fr/faq/menu.json, fr/lang.json
Hi @Atinux!
We have correctly formatted `cached-components.md` in English and we provide the french translation in this PR (with some minor typo fixes) !
=> [Doc EN/FR]: `cached-components.md` review.

en/api/internals-builder.md, en/api/internals-generator.md, en/api/internals-module-container.md, en/api/internals-nuxt.md, en/api/internals-renderer.md, en/api/internals.md
Hi @Atinux !
The English review done along french translation (currently in review ;) )
=> [Doc EN]: api/internals-*.md files review

fr/api/internals-builder.md, fr/api/internals-generator.md, fr/api/internals-module-container.md, fr/api/internals-nuxt.md, fr/api/internals-renderer.md, fr/api/internals.md, fr/api/menu.json
Hi @Atinux,
All Internals part of API translated in French!
Just the api/configuration-* part and all will be done!
=> [Doc FR]: `api/internals*.md` files translated

en/api/internals-nuxt.md
My bad @Atinux , I just do a review of previous PR and see this error.
=> [Doc EN]: Error in title for `internals-nuxt.md`

en/api/configuration-build.md
Hi @Atinux, this is the review of file I made along the translation of configuration-build.md.
=> [Doc EN]: Review of `configuration-build.md`

en/faq/github-pages.md, fr/api/configuration-build.md, fr/api/configuration-loading.md, fr/api/internals-module-container.md, fr/api/menu.json, fr/faq/cached-components.md, fr/faq/github-pages.md, fr/faq/pre-processors.md, fr/guide/commands.md, fr/guide/index.md, fr/lang.json
Hi @Atinux ! New translations an updates !
=> [Doc FR]: Update `github-page.md` (FR/EN) and add french translation for configuration-build.md

en/guide/assets.md
I hope that was a typo and you guys didn't mean 1 Knockout.  😂
=> KO -> KB (typo)

en/examples/menu.json
File was deleted in #319 .
Fixes #346
=> Remove cached components menu link

en/api/pages-fetch.md
Line 70:17
- Syntax Error: Unexpected token, expected (
Line 72:4
- 'store' is not defined
=> Fix some syntax errors

en/api/configuration-generate.md
https://github.com/nuxt/nuxt.js/pull/2032
=> Add documentation for the subFolders option

en/faq/extend-webpack.md
=> Using `isDev` instead of `dev`

en/api/configuration-build.md, es/api/configuration-build.md, fr/api/configuration-build.md, ja/api/configuration-build.md, ko/api/configuration-build.md, zh/api/configuration-build.md
Sorry for the double PR for the same topic, just came across this one.
=> Changing `isDev` in the build configuration

ja/api/components-no-ssr.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/496)
=> Translate ja/api/components-no-ssr.md

en/api/configuration-generate.md, es/api/configuration-generate.md, fr/api/configuration-generate.md, ja/api/configuration-generate.md, ko/api/configuration-generate.md, zh/api/configuration-generate.md
from https://github.com/nuxt/nuxt.js/issues/2704
default values:
https://github.com/nuxt/nuxt.js/blob/6d71770bf4f42c9c7635af386298e43700fb43dd/lib/common/options.js#L229
https://github.com/nuxt/nuxt.js/blob/6d71770bf4f42c9c7635af386298e43700fb43dd/lib/common/options.js#L243
=> Fix default options to configuration-generate section

ja/faq/google-analytics.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/504)
=> Translate ja/faq/google-analytics.md

en/api/configuration-generate.md, en/guide/routing.md
see https://github.com/nuxt/nuxt.js/pull/2698
=> Docs for 'SPA fallback template'

id/api/configuration-head.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/542)
=> Translate id/api/configuration-head.md

id/api/components-nuxt.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/541)
=> Translate id/api/components-nuxt.md

id/examples/custom-routes.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/525)
=> custom-routes.md

id/examples/global-css.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/526)
=> global-css.md

id/examples/hello-world.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/527)
=> hello-world.md

id/examples/layouts.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/529)
=> layouts.md

id/examples/middleware.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/530)
=> middleware.md

id/examples/nested-routes.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/531)
=> nested-routes.md

id/examples/plugins.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/532)
=> plugins.md

id/examples/routes-transitions.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/533)
=> routes-transitions.md

id/examples/seo-html-head.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/534)
=> seo-html-head.md

id/examples/testing.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/535)
=> testing.md

id/examples/vuex-store.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/536)
=> vuex-store.md

id/api/components-no-ssr.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/537)
=> Translate id/api/components-no-ssr.md

id/api/components-nuxt-child.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/538)
=> Translate id/api/components-nuxt-child.md

id/api/components-nuxt-link.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/539)
=> Translate id/api/components-nuxt-link.md

id/api/configuration-loading-indicator.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/540)
=> Translate id/api/configuration-loading-indicator.md

id/guide/views.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/560)
=> Translate id/guide/views.md

en/guide/modules.md
sentence seems grammatically incorrect and long winded...
=> Clarify instructions to check a library

id/guide/assets.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/546)
=> Translate id/guide/assets.md

en/api/components-no-ssr.md, en/api/configuration-css.md, en/api/configuration-dev.md, en/guide/routing.md
Really quick fix @Atinux! Just some `.md` rules for an easilly merging comparison.
EDIT : I added some fix on 3 others files.
=> [Doc EN]: Fix line/type

id/guide/async-data.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/547)
=> Translate id/guide/async-data.md

id/api/pages-validate.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/545)
=> Translate id/api/pages-validate.md

id/api/configuration-css.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/543)
=> Translate id/api/configuration-css.md

id/examples/custom-loading.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/524)
=> Translate id/examples/custom-loading.md

id/examples/async-data.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/523)
=> Translate id/examples/async-data.md

en/api/configuration-render.md
=> Added information how to disable etag

id/guide/commands.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/549)
=> Translate id/guide/commands.md

README.md
A member of Japanese translation community asked me the way to translate. So I have updated readme.
=> Update README about Japanese translation

id/api/configuration-rootdir.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/579)
=> Translate id/api/configuration-rootdir.md

id/api/internals-nuxt.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/578)
=> Translate id/api/internals-nuxt.md

id/api/internals-builder.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/577)
=> Translate id/api/internals-builder.md

id/api/internals-generator.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/576)
=> Translate id/api/internals-generator.md

id/api/internals-renderer.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/575)
=> Translate id/api/internals-renderer.md

id/api/nuxt-render-route.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/574)
=> Translate id/api/nuxt-render-route.md

id/api/nuxt-render.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/573)
=> Translate id/api/nuxt-render.md

id/api/nuxt-render-and-get-window.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/572)
=> Translate id/api/nuxt-render-and-get-window.md

id/api/configuration-plugins.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/571)
=> Translate id/api/configuration-plugins.md

id/api/pages-head.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/570)
=> Translate id/api/pages-head.md

id/api/pages-middleware.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/569)
=> Translate id/api/pages-middleware.md

id/api/index.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/567)
=> Translate id/api/index.md

id/api/pages-scrolltotop.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/565)
=> Translate id/api/pages-scrolltotop.md

id/api/configuration-srcdir.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/557)
=> Translate id/api/configuration-srcdir.md

id/faq/window-document-undefined.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/562)
=> Translate id/faq/window-document-undefined.md

id/api/configuration-dev.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/556)
=> Translate id/api/configuration-dev.md

id/faq/cached-components.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/555)
=> Translate id/faq/cached-components.md

id/faq/async-data-components.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/554)
=> Translate id/faq/async-data-components.md

id/guide/contribution-guide.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/551)
=> Translate id/guide/contribution-guide.md

id/guide/configuration.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/550)
=> Translate id/guide/configuration.md

en/guide/development-tools.md
This was in ES folder, copied to EN
=> added eslint && prettier best practices

id/guide/development-tools.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/552)
=> Translate id/guide/development-tools.md

id/api/configuration-servermiddleware.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/566)
=> Translate id/api/configuration-servermiddleware.md

id/api/configuration-loading.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/564)
=> Translate id/api/configuration-loading.md

id/api/context.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/568)
=> Translate id/api/context.md

id/api/internals.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/584)
=> Translate id/api/internals.md

id/guide/vuex-store.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/559)
=> Translate id/guide/vuex-store.md

id/api/nuxt.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/583)
=> Translate id/api/nuxt.md

id/api/configuration-render.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/582)
=> Translate id/api/configuration-render.md

id/api/configuration-router.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/587)
=> Translate id/api/configuration-router.md

id/api/internals-module-container.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/586)
=> Translate id/api/internals-module-container.md

id/api/pages-fetch.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/585)
=> Translate id/api/pages-fetch.md

id/api/configuration-env.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/558)
=> Translate id/api/configuration-env.md

id/examples/auth-routes.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/id/review/553)
=> Translate id/examples/auth-routes.md

en/faq/heroku-deployment.md
Incorrect English & reads better
=> Removed to from 'recommend you to'

en/guide/vuex-store.md
This is an alternative way to export vuex state, mutations, actions in nuxtjs apart from exporting them as functions. It's similar to the modular function. [See example](https://github.com/nuxt/nuxt.js/tree/dev/examples/vuex-store-modules/store) but without requiring an `index.js` root file.
=> Added documentation for exporting vuex state, mutations, actions as object 

en/examples/auth-external-jwt.md
An example about using JWT authentication with nuxt (with external api webservice)
=> a jwt authentication with nuxt.js example

en/lang.json
Not sure if the other languages should be updated to match the 1.4 release
=> 1.4 got released

it/api/components-nuxt-child.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/599)
=> Translate components-nuxt-child.md via GitLocalize - API

it/api/components-no-ssr.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/598)
=> Translate components-no-ssr.md via GitLocalize - ITA

it/examples/auth-routes.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/650)
=> Translate auth-routes.md via GitLocalize - ITA

it/examples/async-data.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/635)
=> Translate async-data.md via GitLocalize - ITA

it/examples/custom-loading.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/636)
=> Translate custom-loading.md via GitLocalize - ITA

it/examples/custom-routes.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/648)
=> Translate custom-routes.md via GitLocalize - ITA

it/examples/global-css.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/644)
=> Translate global-css.md via GitLocalize - ITA

it/examples/hello-world.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/637)
=> Translate hello-world.md via GitLocalize - ITA

it/examples/i18n.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/646)
=> Translate i18n.md via GitLocalize - ITA

it/examples/layouts.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/647)
=> Translate layouts.md via GitLocalize - ITA

it/examples/middleware.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/645)
=> Translate middleware.md via GitLocalize - ITA

it/examples/nested-routes.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/643)
=> Translate nested-routes.md via GitLocalize - ITA

it/examples/plugins.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/638)
=> Translate plugins.md via GitLocalize - ITA

it/examples/routes-transitions.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/639)
=> Translate routes-transitions.md via GitLocalize - ITA

it/examples/seo-html-head.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/640)
=> Translate seo-html-head.md via GitLocalize - ITA

it/examples/testing.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/641)
=> Translate testing.md via GitLocalize - ITA

it/examples/vuex-store.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/it/review/642)
=> vuex-store.md - ITA

en/api/internals-builder.md, en/api/internals-generator.md, en/api/internals-nuxt.md, en/api/internals-renderer.md, en/api/internals.md, en/guide/modules.md
Add documentation for hooks. @pi0 @Atinux hooks haven't been documented so far. So I made a first attempt. But I need you guys to review. There is not much about hooks anywhere, they are least known part of nuxt. It will be good to give them good coverage. I went though source code and listed all the hooks I could find in the code. It will be good to add description for some of them I was not sure what they do.
Thanks
=> Add Hooks documentation

en/examples/menu.json, ja/examples/auth-external-jwt.md, ja/examples/menu.json
I have added [a jwt authentication with nuxt.js example by ahadyekta · Pull Request #327 · nuxt/docs](https://github.com/nuxt/docs/pull/327) to menus.
=> Add a jwt authentication with nuxt.js example to menus

en/api/configuration-build.md, ja/api/components-no-ssr.md, ja/api/configuration-build.md, ja/api/configuration-router.md, ja/api/menu.json, ja/lang.json
I have updated docs to fix GitLocalize conflicts.
=> Fix GitLocalize conflicts

en/api/internals-renderer.md
See https://github.com/nuxt/nuxt.js/issues/1688#issuecomment-374883057
=> add render:errorMiddleware info

ja/api/configuration-generate.md
=> fix spell miss: 'generete'

en/api/internals-generator.md
Hi, I filled the empty cells for the generation hook arguments and their description.
=> feat: complete docs for genreation hooks

en/faq/pre-processors.md, es/faq/pre-processors.md, fr/faq/pre-processors.md, ja/faq/pre-processors.md, ko/faq/pre-processors.md, zh/faq/pre-processors.md
coffee-script used instead of coffeescript
=> Typo package name

ru/faq/google-analytics.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ru/review/700)
=> Translate ru/faq/google-analytics.md

ja/guide/menu.json
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/692)
=> Update  ja/guide/menu.json

ja/guide/modules.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/691)
=> Update  ja/guide/modules.md

ja/guide/vuex-store.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/690)
=> Update  ja/guide/vuex-store.md

en/api/components-no-ssr.md
```html
<no-ssr placeholder="Loading...">
<comments />
</no-ssr>
```
```html
<no-ssr>
<comments />
<comments-placeholder slot="placeholder">
</no-ssr>
```
| Text placeholder | Slot placeholder | 
|:-:|:-:|
| Loading...  | ![captura de tela de 2017-11-24 12-28-07](https://user-images.githubusercontent.com/1490347/33214415-fe2894fe-d112-11e7-9be9-2f0d873e4a82.png) |
=> Update <no-ssr /> component guide

en/api/pages-fetch.md, en/api/pages-watchquery.md, en/guide/async-data.md
Add missing `watchQuery` documentation :relaxed: 
Related: https://github.com/nuxt/nuxt.js/issues/2591
=> Add watchQuery information

ja/faq/css-flash.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/755)
=> Update  ja/faq/css-flash.md

ja/faq/host-port.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/758)
=> Update  ja/faq/host-port.md

ja/faq/surge-deployment.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/738)
=> Update  ja/faq/surge-deployment.md

ja/api/configuration-css.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/710)
=> Update  ja/api/configuration-css.md

ja/guide/index.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/709)
=> Update  ja/guide/index.md

ko/guide/development-tools.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ko/review/1359)
=> translate guide/development-tools.md into Korean 

en/guide/development-tools.md
This PR contains some grammar fixes for the English development tools guide.
=> Dev Tools Grammar Fixes

zh/api/configuration-build.md
中文意思好像自动上传文件到CDN上 ，其实还是要手动传文件到CDN，只是文件地址映射到CDN而已！翻译误解
=> Translation optimization

en/guide/index.md
=> Typo in Introduction

ja/faq/nginx-proxy.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/1064)
=> Update  ja/faq/nginx-proxy.md

ko/api/nuxt.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ko/review/2868)
=> translate api/nuxt.md into Korean

ko/api/index.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ko/review/2870)
=> translate api/index.md into Korean

ko/guide/index.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ko/review/2866)
=> translate guid/index.md into Korean

en/faq/menu.json, en/faq/netlify-deployment.md
Hey folks,
Here's an initial pass at a guide for deploying to Netlify. I've had a great experience recently and though things are straight forward, I figure an extra guide couldn't hurt in case someone comes looking for it.
=> Netlify Deployment Guide

ja/api/pages-fetch.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/4524)
=> Update  ja/api/pages-fetch.md

en/guide/routing.md
I'm starting to learn Vue with Nuxt, and the docs didn't mention how to use the routes generated here.
=> Suggestion for showing how to use these routes

ja/api/configuration-loading-indicator.md
I translated the contents of the following pages from English to Japanese.
https://ja.nuxtjs.org/api/configuration-loading-indicator
=> Translate en to ja configuration-loading-indicator.md

ja/api/internals.md
=> Translation to Japanese of api/internals.md

ja/api/internals-nuxt.md
api/internals-nuxt.md の日本語への翻訳
=> Translation of api/internals-nuxt.md into Japanese

en/guide/views.md
Relates to [https://github.com/nuxt/nuxt.js/pull/3629/files](https://github.com/nuxt/nuxt.js/pull/3629/files)
=> Add documentation for loading: false

ja/api/configuration-dev.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/5321)
=> Update  ja/api/configuration-dev.md

ja/api/configuration-builddir.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/5266)
=> Update  ja/api/configuration-builddir.md

en/api/configuration-vue-config.md
=> Document vue.config property

en/faq/host-port.md
=> Document host retrieval changes

en/guide/plugins.md
related: nuxt/nuxt.js/issues/2233
=> Improve inject documentation

en/api/configuration-render.md
See https://github.com/nuxt/nuxt.js/pull/3671
=> Add docs for render.dist options

ja/api/configuration-mode.md
translate https://ja.nuxtjs.org/api/configuration-mode
=> Translate configration-mode JA docs

en/guide/plugins.md
related: https://github.com/nuxt/docs/pull/694#issuecomment-412801655
=> Fix inject new reserved keyword

en/api/configuration-generate.md
Doc PR for https://github.com/nuxt/nuxt.js/pull/3725
=> [2/2] Do not remove optional tags

zh/api/configuration-dev.md
=> server.js文件报错，说Nuxt is not a constructor

fr/faq/google-analytics.md
=> [Fix] FR docs : typo fix

de/faq/cached-components.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/de/review/6819)
=> DE: Translate cached-components.md

de/faq/async-data-components.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/de/review/5864)
=> DE: Translate async-data-components.md 

de/faq/host-port.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/de/review/6758)
=> DE: Translate host-port.md

en/api/configuration-router.md
AFAIK. https://nuxtjs.org/api/
=> Context not present in `data`, only in `asyncData`

ja/api/pages-layout.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/6825)
=> Update  ja/api/pages-layout.md

ja/faq/dokku-deployment.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/6859)
=> Update  ja/faq/dokku-deployment.md

ja/api/configuration-modules.md
@potato4d @inouetakuya 
I have translateted `ja/api/configuration-modules.md`.
please review.
thanks.
=> ja: Update ja/api/configuration-modules.md

ja/faq/host-port.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/6875)
=> ja: Update ja/faq/host-port.md

ja/api/pages-head.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/6876)
=> ja: Update ja/api/pages-head.md

ja/api/configuration-dev.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/6891)
=> ja: Update ja/api/configuration-dev.md

ja/api/internals-nuxt.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/6893)
=> ja: Update ja/api/internals-nuxt.md

ja/guide/development-tools.md
コード例の追加と一部翻訳の修正（files →ファイル）を行いました。
`Isomorphic application` は訳さないほうが良いと思い、そのままにしています。
お手すきの際にレビューよろしくお願いします。
=> ja: Update ja/guide/development-tools.md

en/guide/plugins.md
`inject` wasn't being used. Now it is ;)
=> Corrected injection example

ja/api/configuration-dev.md
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/100/ja/review/7188)
=> ja: Update  ja/api/configuration-dev.md

ja/api/configuration-vue-config.md, ja/api/menu.json
`ja/api/configuration-vue-config.md` を翻訳しました。
jaの方に最初ファイルがなかったので、enの方から持ってきて翻訳しました -> af835e1490f696df87b0c6bba3c30b3f8337b845
レビューよろしくお願いいたします。
=> ja: Update ja/api/configuration-vue-config.md 

ja/api/configuration-modulesdir.md, ja/api/menu.json
`ja/api/configuration-modulesdir.md` を翻訳しました。
ja には最初ファイルがなかったので、 df388a4178fe0eb9668c2b9d36d699b8cc9a3784  で追加しました。
レビューよろしくお願いいたします。
=>  ja: Update ja/api/configuration-modulesdir.md 

en/api/configuration-build.md, en/api/configuration-generate.md
https://github.com/nuxt/nuxt.js/pull/3965
=> docs(build): add changes concerning minify and html.minify

de/api/menu.json, en/api/menu.json, fr/api/menu.json
I have added api/configuration-modulesdir to menu if the file exists.
=> Add api/configuration-modulesdir to menu

zh/guide/installation.md
Nuxt.js install create-nuxt-app Use a tutorial
=> Nuxt 2.0 install

de/api/menu.json, en/api/menu.json, fr/api/menu.json
I have added api/configuration-vue-config to menu if the file exists.
=> Add api/configuration-vue-config to menu

en/api/pages-watchquery.md
Source: https://github.com/nuxt/nuxt.js/blob/master/lib/app/client.js#L121
=> Add watchQuery: true

en/api/configuration-build.md
@clarkdo @pi0 @Atinux anything left to update here?
=> Remove section on build.vendor

en/guide/assets.md
Due to upgrade of CSS loader and my issue https://github.com/nuxt/nuxt.js/issues/3931 I think we should update documentation so we don't mislead newcomers
=> Actualize info about css-loader

ko/guide/development-tools.md
=> spelling correction

en/examples/auth-external-jwt.md
Making sure that it: 
- The source code reflects the documentation and matches
- The instruction also documents how to logout.
=> Update the JWT External Authenticate pages

en/guide/contribution-guide.md
* Correct preselected library (nuxt.js) for issue CTMY link
* Information about the test structure (what are fixtures, why you have to rebuild, ...)
* Information about linting and examples
* Minor tweaks
Resolves https://github.com/nuxt/docs/issues/788
=> docs(contribution): update contribution guide

en/api/internals-module-container.md, en/faq/window-document-undefined.md, en/guide/configuration.md, en/guide/plugins.md, en/guide/vuex-store.md
Fully resolves https://github.com/nuxt/docs/issues/781
=> docs(vendor): remove vendor mention where applicable and add deprecate warnings

en/api/configuration-build.md
Related: https://github.com/nuxt/nuxt.js/pull/3705
=> docs(build): add quiet parameter

ja/api/configuration-router.md
ja/api/configuration-router.md を翻訳しました。
お手すきの際にレビューよろしくお願いします。
修正概要
- 追加分の翻訳
- リンクの修正
- サンプルコードの修正
=> ja: Update ja/api/configuration-router.md

en/api/components-nuxt-child.md
Adds nuxt-child example on keep-alive and keep-alive-props.
Related nuxt.js PR: https://github.com/nuxt/nuxt.js/pull/4067
=> en: update nuxt-child en/api/components-nuxt-child.md

ja/api/internals-module-container.md
@inoutakuya @potato4d @aytdm
`ja/api/internals-module-container.md` を翻訳しました。
レビューよろしくおねがいします 🙏
=> ja:update ja/api/internals-module-container.md

en/api/components-nuxt-link.md
Update en/api/components-nuxt-link.md
Fix `<router-link>` url.
=> en: Fix '<router-link>' url

ja/api/nuxt-render-and-get-window.md
@inouetakuya  @potato4d  @aytdm 
着手が遅くなってしまいすみません!!
ja/api/nuxt-render-and-get-window.md
の差分としては、 **コード例の修正** のみでした。
とくに翻訳の必要はありませんでした。
ご確認よろしくおねがいします🙏
=> ja: Update ja/api/nuxt-render-and-get-window.md

en/faq/host-port.md
=> Add note about random open port assignment

ja/api/configuration-transition.md
遅くなってすいません。
`ja/api/configuration-transition.md` を翻訳いたしました。
お手すきの時に、レビューよろしくお願いいたします。
残りも順次 PR出していきます。
=> ja: Update ja/api/configuration-transition.md 

en/guide/installation.md, zh/guide/installation.md
add ant-design-vue guide 
submited pull request of create-nuxt-app [https://github.com/nuxt/create-nuxt-app/pull/110]
=> add ant-design-vue guide

zh/api/index.md
update docs to latest version.
=> docs: update docs

zh/lang.json
Update the Chinese document version number to synchronize with the latest English official website version number.
更新中文文档版本号，与最新英文官网版本号同步。
=> fix verson, Synchronize with the English official website version number

ja/api/configuration-servermiddleware.md
`ja/api/configuration-servermiddleware.md` を翻訳いたしました。
お手すきの時にでもレビューよろしくおねがいしますー
=> ja: Update ja/api/configuration-servermiddleware.md

en/api/index.md
Hi, I was struggling at understanding why the asyncData function doesn't always load server-side.
Basing on this explanation: https://github.com/nuxt/nuxtjs.org/issues/106#issuecomment-360808831 (who made me understand how nuxtjs works), I decided to try a different way of describing the function, hopefully helping peoples with the same problem.
=> Explaining function behaviour in a clearer way

en/api/configuration-render.md
Documentation to the https://github.com/nuxt/nuxt.js/pull/4198
=> - feat: documentation of custom pushAssets function

en/guide/contribution-guide.md
Reference: https://github.com/nuxt/nuxt.js/pull/4216
=> improve(en): contribution-guide.md

ja/api/configuration-generate.md
`ja/api/configuration-generate.md` の翻訳 PR となります。お願いいたします :pray:
=> ja: Update configuration generate.md

ja/api/configuration-loading.md
`ja/api/configration-loading.md` の翻訳 PR です 🙏
=> ja: Update configuration loading

en/guide/routing.md, ja/api/configuration-env.md
たいへん遅くなりました。すみません。
ja/api/configuration-env.md を翻訳しました。
レビューよろしくおねがいします 🙏
=> ja: Update ja/api/configuration-env.md 

ja/guide/plugins.md
`ja/guide/plugins.md`の翻訳PRです。レビューお願い致します🙏
=> ja: Translate plugins.md

ja/guide/installation.md
ja/guide/installation.mdを翻訳しました。
レビューをよろしくお願いします
=> ja: Update ja/guide/installation.md

en/guide/commands.md
Add description of unix socket.
=> en: Update en/guide/commands.md

en/api/internals.md
@manniL 
Hi,
Some links are 404, so I fixed that.
Could you review this PR? correct URLs?
Fix url and link text in brackets below:
+ renderer.js
+ options.js
=> en: Fix url of en/api/internals.md

ja/guide/commands.md
ja/guide/commands.mdの翻訳アップデートPRです。
レビューをよろしくお願い致します🙏
=> ja: Update ja/guide/commands.md

en/faq/postcss-plugins.md
Resolves: #841 
API is already properly documented
=> feat(en): update postcss plugin faq

ja/api/configuration-server.md
`ja/api/configuration-server.md` の翻訳です。レビューお願い致します🙏
=> ja: translate configuration-server.md

ja/guide/modules.md
Same as the title.
'w' is typo ?
=> fix(ja): typo

id/api/configuration-mode.md
translation indonesia for configuration-mode guide
=> id: adding configuration-mode trans

en/faq/heroku-deployment.md
The most notable area of improvement is adding notes regarding the Procfile.
=> Updates the heroku deployment documentation

en/api/configuration-loading-indicator.md, en/guide/views.md, ja/api/configuration-loading-indicator.md
repull-request #971 
change 'https://github.com/nuxt/nuxt.js/tree/dev/packages/app/template' to 'https://github.com/nuxt/nuxt.js/tree/dev/packages/vue-app/template'
=> fix invalid links

en/guide/assets.md
=> Formatting code snippet in "warning" as required

en/faq/appengine-deployment.md, en/faq/menu.json
I also wrote this article on Medium that goes a little further:
https://medium.com/@pascalluther/deploying-a-nuxt-js-v2-app-to-google-app-engine-google-cloud-platform-69c9008531bc
But I think for the docs this one here is more appropriate.
=> Add Google App Engine deployment FAQ

en/api/configuration-render.md, en/api/menu.json
=> feat(api, en): fallback option

en/api/configuration-modern.md, en/api/menu.json
=> doc: add modern build

en/api/configuration-build.md, en/api/configuration-generate.md, en/api/menu.json
=> feat(api, en): devtools option

ja/api/configuration-servermiddleware.md
Fix a broken sentence as japanese
=> ja: Fix a broken sentence as japanese

ja/guide/commands.md
未翻訳箇所と翻訳済みの箇所を一部修正しました。
お手すきの際にレビューをお願いします。
=> ja: Update guide/commands.md

zh/api/components-nuxt-child.md, zh/api/components-nuxt.md, zh/api/configuration-css.md, zh/api/configuration-global-name.md, zh/api/configuration-modern.md, zh/api/menu.json, zh/api/pages-head.md, zh/api/pages-middleware.md, zh/guide/assets.md, zh/guide/async-data.md, zh/lang.json
* 增加**教程**中assets目录与asyncData严谨性
* 添加缺失代码片段
* 增加**API**缺失页面
* 更好的阅读体验
* fix guide assets, asyncData
* Add missing pages
* Fix missing code snippets for some modules in the API
* better experience
=> Chinese official website upgrade to 2.3.x and English official website synchronization

zh/api/configuration-loading.md
zh :fix extra dot in loading doc
this.$nuxt.$.loading.finish() -> this.$nuxt.$loading.finish()
=> zh: Fix extra dot in loading.md

zh/guide/commands.md
Add command examples of development and deploy for custom Node.js server.
=> zh -  refactor: commands list

ja/api/components-nuxt-child.md
遅くなりました 🙏 
以下の翻訳です。
https://github.com/nuxt/docs/blob/master/en/api/components-nuxt-child.md
レビューお願いします。
=> ja: Update components-nuxt-child.md

zh/guide/commands.md
=> 生成模式=>生产模式

zh/faq/http-proxy.md
http proxy for cross-domain resource requests in nuxt.js
=> zh: Create http-proxy.md

ja/api/pages-head.md
=> ja: fix fill article

ja/faq/deployment-aws-s3-cloudfront.md, zh/faq/menu.json
Here are two snags that broke running in development.
Maybe we could setup prettier to check all YAML/JSON.
=> Bugs found in YAML Front-Matter and JSON menu.

zh/api/configuration-build.md
change style-resources's  configuration docs
=> 修改 style-resources 使用和依赖说明

en/guide/contribution-guide.md, ja/guide/contribution-guide.md
=> fix nuxt command `bin/nuxt` to `yarn nuxt`

zh/api/configuration-css.md
=> 修正 object 格式错误

zh/faq/http-proxy.md
'@nuxtjs/proxy' need use axios 'proxy: true'
=> change http-proxy examples for zh

en/api/configuration-build.md, en/api/menu.json
=> en: friendlyErrors

en/api/configuration-hooks.md, en/api/configuration-router.md
=> en: Add Hooks use-case when changing router.base (related #984)

en/api/configuration-build.md
=> Fix 'JavaScript' typo in configuration-build.md

id/guide/installation.md
The previous one is outdated, so i propose this update to help other developers understand the latest nuxt
=> Indonesian - Installation Guide Updates

de/api/components-no-ssr.md, en/api/components-no-ssr.md, fr/api/components-no-ssr.md, ja/api/components-no-ssr.md, zh/api/components-no-ssr.md
https://github.com/egoist/vue-no-ssr/commit/fa116940930e713704960b2c1d05a45c378a9b1f#diff-04c6e90faac2675aa89e2176d2eec7d8
=> remove outdated note

en/api/configuration-modern.md
After watching Sebastien Chopin (https://youtu.be/-Z1hI4Wxblo), I thought it would be nice to have that information in the docs.
=> en: modern mode with nuxt generate

id/guide/installation.md
i'm sorry i used prettier formatter on my vs code and when i saved theh file the extension formatted the whole file and i didn't notice the indentation changes on the list, this update should fix it, thank you
=> List indentation fixes

en/guide/vuex-store.md, ja/guide/vuex-store.md
I found this while checking the docs
=> fix: generated namespaced code sample

en/api/menu.json, en/api/pages-loading.md
Docs for https://github.com/nuxt/nuxt.js/pull/4786
=> en: Add docs for loading property

en/guide/configuration.md
Just a few fixes here and there to improve grammar and overall consistency.
=> Minor grammar/consistency tweaks to Configuration page

en/api/configuration-modulesdir.md
nodeExternal --> nodeExternals
=> docs(modulesDir): fix typo

en/api/components-nuxt-link.md
All this PR does is fix a simple typo.
P.S. I'd like to be involved in helping with the docs or reviewing them if possible.
=> refactor: fix typo

en/guide/plugins.md
https://nuxtjs.org/guide/plugins#name-conventional-plugin
=> docs: fix code block missing ending delimiter

en/api/configuration-build.md
=> doc: fix typo

en/api/configuration-router.md
Fix typo in configuration-router.md
=> Fix typo in config router readme

en/guide/index.md
After the altered sentence we have "It will build a Static Generated Vue.js Application." Which has a better grammatical style. Now the preceding sentence follows this standard.
=> docs: improve sentence grammar

ja/api/configuration-build.md
=> ja: Fix missing translation

en/api/configuration-servermiddleware.md
Edit readme to clear things up a bit about usage. Previous wording was a bit confusing that muddled my understanding a bit.
=> Edit grammar and clarify serverMiddleware usage

ja/api/configuration-modern.md, ja/api/menu.json, ja/api/pages-loading.md, ja/examples/menu.json, ja/examples/named-views.md, ja/faq/appengine-deployment.md, ja/faq/http-proxy.md, ja/faq/ios-phone-numbers.md, ja/faq/menu.json, ja/guide/menu.json
@inouetakuya @potato4d I added  these files not exists under ja directory for translation.
=> ja: Add files not exists under ja directory and Update ja/**/menu.json

ja/api/components-no-ssr.md
=> ja: Fix typo in components-no-ssr.md

ja/faq/github-pages.md
vuejs-jp#70 の差分の翻訳が完了しました。
ソースコードのみの修正でした。
=> ja: Translate faq/github-pages.md

ja/guide/directory-structure.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/45 の差分の翻訳が完了しました。
=> ja: Translate directory-structure.md

ja/guide/configuration.md
ja/guide/configuration.md を翻訳しました。
レビューよろしくお願いいたします。
https://gist.github.com/inouetakuya/4b231c5e634e5e7d0f80856d3eb3691d#file-git-diff-en-diff-L3348
上記差分と現状の日本語を訳を確認する限りは、ほとんどは既に対応済みだったようです。新しいオプションの分だけ日本語訳を追加しました。
Related issue https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/42
=> ja: Update ja/guide/configuration.md

ja/api/configuration-hooks.md
vuejs-jp#93 の差分の翻訳が完了しました。
こちら、ご確認お願いいたします。
`en` との差分はこちらになります。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-e292c6513919b3bcc3cb403f5a0460b7
=> ja: Translate api/configuration-hooks

ja/faq/heroku-deployment.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/68 の差分について翻訳しました。
レビューよろしくおねがいします 🙇
=> ja: Update faq/heroku-deployment.md

ja/api/configuration-loading.md
vuejs-jp#96 の差分の翻訳が完了しました。
こちら、ご確認お願いいたします。
en との差分はこちらになります。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-83c2ef26e99b53d0255c03b572773242
=> ja: Translate api/configuration-loading

README.md, zh/examples/auth-external-jwt.md, zh/examples/custom-page-loading.md, zh/examples/menu.json, zh/examples/named-views.md, zh/examples/typescript-vuex.md, zh/examples/typescript.md
* Update Chinese document sample module
* add primary maintainer
=> Update Chinese document sample module and add primary maintainer

ja/api/configuration-servermiddleware.md
@inouetakuya @potato4d @aytdm
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/104 の差分の修正が完了しました。
=> ja: Fix sample code

ja/api/pages-watchquery.md
[vuejs-jp#125](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/125) の差分の翻訳が完了しました。
=> ja: Translate pages-watchquery.md

ja/api/configuration-builddir.md
コード例のみの更新でした。お手すきの際にご確認よろしくお願いします。（翻訳がないものを私の方でいくつか巻き取っています）
対応する issue：https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/85
=> ja: Update api/configuration-builddir.md

ja/api/configuration-css.md
対応する issue：https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/86
=> ja: Update api/configuration-css.md

ja/api/configuration-generate.md
=> ja: Update api/configuration-generate.md

ja/faq/duplicated-meta-tags.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/73 の翻訳(追従)が完了しました。
スタイルが多少変更されていたため、その部分だけ対応を行いました。
=> ja: Translate faq/duplicated-meta-tags

ja/faq/http-proxy.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/66 の翻訳が完了しました。
=> ja: Translate faq/http-proxy

ja/faq/window-document-undefined.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/56 の翻訳が完了しました。
=> ja: Translate faq/window-document-undefined

ja/faq/surge-deployment.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/58 の翻訳が完了しました。
=> ja: Translate faq/surge-deployment

ja/faq/menu.json
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/55 の翻訳が完了しました。
今回翻訳したタイトルについては、以下を参考にしています。
- iOS と電話場号(マージ済み)
- https://github.com/nuxt/docs/pull/1207
- Google App Engine へデプロイするには？(プルリク承認済み、未マージ)
- https://github.com/nuxt/docs/pull/1194
- クロスオリジンリソースを共有するには？(未マージ)
- https://github.com/nuxt/docs/pull/1206
=> ja: Translate faq/menu.json

ja/api/internals.md
対応する issue：https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/115
=> ja :Update api/internals.md

ja/api/configuration-modules.md
=> ja: Update api/configuration-modules.md

ja/api/configuration-transition.md
=> ja: Update api/configuration-transition.md

ja/api/configuration-srcdir.md
=> ja: Update api/configuration-srcdir.md

ja/api/configuration-plugins.md
=> ja: Update api/configuration-plugins.md

ja/examples/i18n.md
vuejs-jp#77 の差分の翻訳が完了しました。
enの差分はこちらです。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-180cada088b14ae076e525266b7b393e
=> ja: Translate examples/i18n.md

ja/faq/extend-webpack.md
お手すきの際にレビューよろしくお願いします
対応する issue：https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/72
=> ja: Update faq/extend-webpack.md

ja/faq/pre-processors.md, ja/faq/webpack-plugins.md
お手すきの際にレビューよろしくお願いします
対応する issue：https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/57
=> ja: Update faq/webpack-plugin.md

ja/guide/development-tools.md
お手すきの際にレビューよろしくお願いします
対応する issue：https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/44
=> ja: Update guide/development-tools.md

ja/guide/modules.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/48 こちらの翻訳になります！
レビューお願いしたします 🙏 
en の差分はこちらです。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-7c901fa8778b618080258eddf66b6889
=> ja: Translate en/guide/modules.md to ja

ja/api/menu.json
vuejs-jp#116 の日本語訳です。レビューお願いします。
=> ja: Translate api/menu.json

ru/guide/routes-transitions.md
=> ru: Update routes-transition.md

ja/examples/named-views.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/76
こちらの日本語訳です。よろしくお願いいたします。:cat: 🙏
=> ja: Translate examples/named-views

ja/faq/nginx-proxy.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/62
上記Issueの日本語訳です。よろしくお願いいたします 🐱
=> ja: Translate faq/nginx-proxy.md

ja/examples/auth-external-jwt.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/79
こちらの日本語訳です。よろしくお願いいたします 🐱
=> ja: Translate examples/auth-external-jwt

en/guide/menu.json
The anchor is not working due this name mismatch
=> Assets.Webpack instead of Webpacked

en/api/index.md
I've fixed a grammatical error in the page so it reads slightly better.
=> Grammar fix in last paragraph

en/guide/development-tools.md
export default not recognized so changed with module.exports
=> export default to module.exports

ja/guide/index.md
Issue
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/46
en doc
01cd8163acdb0e7ffbed35854a821a1aa8bb24e1
確認をお願いします！
=> ja: Update guide/index.md

de/lang.json, en/lang.json, es/lang.json, fr/lang.json, id/lang.json, ja/lang.json, ko/lang.json, pt-BR/lang.json, ru/lang.json, zh/lang.json
See first: [/nuxt/nuxtjs.org/issues/178](/nuxt/nuxtjs.org/issues/178)
Use language resource at the homepage (top page).
This pull request includes:
- Add [/nuxt/nuxtjs.org](/nuxt/nuxtjs.org) homepage resources
=> Add language resource for homepage

ja/faq/postcss-plugins.md
遅くなりましてすみません。
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/60 を翻訳しましたので、ご確認お願いいたします 🙏 
最新の en はこちらです。
https://github.com/nuxt/docs/blob/master/en/faq/postcss-plugins.md
以下のコミットも含めて、最新の en を翻訳しました。
https://github.com/nuxt/docs/commit/3f6f2d363658c76356f5e40f5bc3c53aeb62f0f9
（ https://github.com/nuxt/docs/pull/1276#issuecomment-477933093 のコメントを拝見し、判断しました。）
=> ja: Translate faq/postcss-plugins.md

ja/faq/netlify-deployment.md
=> ja: replace asterisks with underscores

en/examples/menu.json, ja/examples/menu.json, zh/examples/menu.json
Add "Named Views" to `*/examples/menu.json` if `*/examples/named-views.md` exists. 😄
=> Add "Named Views" menu to  examples

ja/api/configuration-modulesdir.md
`ja/api/configuration-modulesdir.md` ( vuejs-jp#99 )を更新しました。
お手数ですがご確認お願いいたします。
=> ja: Update ja/api/configuration-modulesdir.md

ja/api/configuration-dir.md
`ja/api/configuration-dir.md` ( vuejs-jp#88 )を更新しました。
お手数ですがご確認お願いいたします。
=> ja: Update ja/api/configuration-dir.md

ja/api/configuration-build.md
`ja/api/configuration-build.md` ( vuejs-jp#84 )を更新しました。
該当のファイルに変更はなかったようですが、実際のファイルを見比べると更新した方が良い部分があったのでご確認お願いします。
=> ja: Update ja/api/configuration-build.md

ja/guide/assets.md
refs: vuejs-jp#39 の翻訳をいたします。
今回の翻訳範囲の英語の原文はこちらで確認できます。
https://github.com/nuxt/docs/commit/a522919f53e8f6a2fff4157074196e56f516ee64
ある程度翻訳が終わったらDraftから切り替えます。
=> ja: Translating ja/guide/assets

ja/faq/deployment-aws-s3-cloudfront.md
@inouetakuya @aytdm @potato4d 
[vuejs-jp#74](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/74) の翻訳をしました。
最新の en doc はこちらです。
https://github.com/nuxt/docs/blob/master/en/faq/deployment-aws-s3-cloudfront.md
（前回よりいくつかコミットされていたようなので、最新の en doc を参考にしました）
遅くなってすみませんがご確認お願いします！🙏
=> ja: Translate faq/deployment-aws-s3-cloudfront.md

en/guide/menu.json, en/guide/typescript.md
Follows https://github.com/nuxt/nuxt.js/pull/5412 changes
=> docs(ts): update TS docs & add anchors to menu

de/guide/views.md, en/guide/views.md, es/guide/views.md, fr/guide/views.md, id/guide/views.md, ja/guide/views.md, ko/guide/views.md, pt-BR/guide/views.md, zh/guide/views.md
The HEAD_ATTRS placeholder wasn't documented, I've added  it to reflect the current structure of app.template.html
=> Add missing HEAD_ATTRS placeholder

ja/homepage/why.md
=> ja: Translate homepage/why.md

ja/homepage/why_enjoyable.md
=> ja: Translate homepage/why_enjoyable.md

ja/homepage/why_performant.md
=> ja: Translate homepage/why_performant.md

en/guide/installation.md
'developement' => 'development'
=> Fixed spelling error.

ja/guide/views.md
すみません。いくつか不備が見つかったので翻訳を修正しました。
お手数ですが、ご確認お願い致します。
=> ja: Translate guide/views.md

en/guide/installation.md
Hi everyone!
I was just going through the docs and found this link that was not working (anymore?). Now i'm not sure if they link i added is the correct one either, so feel free to edit :)
=> Fix link to Nuxt mode

en/faq/heroku-deployment.md, en/faq/netlify-deployment.md, en/guide/directory-structure.md, en/guide/index.md, en/guide/routing.md, en/guide/views.md, en/guide/vuex-store.md
This PR adds links to lessons from the free Nuxt.js Fundamentals course that was created together with the Nuxt.js team.
I've added a [screenshot](https://i.imgur.com/QfpBBFD.png) for your convenience.
**IMPORTANT:**
The CSS needed for these banners are in [PR#182](https://github.com/nuxt/nuxtjs.org/pull/182) of the nuxtjs.org repository. PR#182 **must be merged** before this is.
=> Link to free lessons from the Nuxt.js Fundamentals video course

en/api/menu.json, ja/api/configuration-build.md, ja/api/menu.json, ja/guide/menu.json, ja/guide/typescript.md
Reflect [docs: TypeScript Support section by kevinmarrec · Pull Request #1202 · nuxt/docs](https://github.com/nuxt/docs/pull/1202) to Japanese.
We will translate them later (another PR) :sweat_smile:
=> ja: Add guide/typescript.md to ja/

zh/api/nuxt-render.md
Seems like Nuxt updated nuxt.render and nuxt.build usages as well as english doc, but chinese doc haven't updated yet.
=> zh: update chinese nuxt-render.md to fit new version

zh/guide/modules.md
=> zh: Fix  guide/modules.md link error

zh/guide/assets.md
=> zh:Update assets.md

fr/guide/plugins.md
Fix typo Acutellement -> Actuellement
=> fr: Update guide/plugins.md

en/api/configuration-render.md
I've added a complete CSP example with support for Google Analytics, Sentry.io, and LogRocket.io support.
=> added extended CSP example

ja/lang.json
Added `homepage/index.md` and updated `lang.json`. If you have a better translation idea about `welcome`, please give me some advice! :pray:  (I think it might be better to use the original...)
=> ja: Update around the toppage

en/api/configuration-servermiddleware.md
=> en: add prefix option to server middleware

de/lang.json, en/lang.json, es/lang.json, fr/lang.json, id/lang.json, pt-BR/lang.json
Changed `occured ` to `occurred`.
related issue: https://github.com/nuxt/nuxtjs.org/pull/186
=> fix(docs): typo

README.md
ref: [Nuxt.js 公式ドキュメント日本語翻訳ガイドを作成する · Issue #146 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/146)
=> Add the link to the Japanese translation guide

ja/guide/typescript.md
resolve: [[doc] docs(ts): remove unused code in snippets · Issue #140 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/140)
=> ja: docs(ts): remove unused code in snippets

ja/faq/deployment-aws-s3-cloudfront.md
resolve: [[doc] Update deployment-aws-s3-cloudfront.md · Issue #145 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/145)
=> ja: Update faq/deployment-aws-s3-cloudfront.md

ja/guide/installation.md
resolve: [[doc] Fix mode link · Issue #134 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/134)
=> ja: fix mode link

ja/guide/menu.json, ja/guide/typescript.md
ref: [ja: Add guide/typescript.md to ja/ by inouetakuya · Pull Request #1325 · nuxt/docs](https://github.com/nuxt/docs/pull/1325)
=> ja: Translate ja/guide/typescript

ja/guide/development-tools.md
` export default { ` to ` module.exports = { `
=> ja: fix a bug in .eslintrc.js

ja/faq/menu.json, ja/faq/webpack-audio-files.md
I updated `ja/faq/menu.json` and added `ja/faq/webpack-audio-files.md`
Please review them 🙇
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/155, resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/154, resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/153
=> ja: Add webpack audio files

en/guide/commands.md
Order of mention should match order of description.
SSR needed to be defined or more clearly explained. There was no clear indication what SSR meant, what it stands for and for which explanation was relevant.
=> docs(commands): Update commands.md

en/api/configuration-servermiddleware.md
Discussion: https://github.com/nuxt/docs/commit/63de63c176d00dffafe75a218314e150045e1cf6#r33457036
=> flip router base and serverMiddlewarePath

ja/guide/typescript.md
@inouetakuya @potato4d 未翻訳部分も併せて翻訳しました。レビューよろしくお願いします。
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/135
=> ja: update guide/typescript.md

ja/api/configuration-render.md
@inouetakuya @potato4d レビューよろしくお願いします:pray:
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/143
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/161
=> ja: update-api-configuration-render.md

en/api/configuration-build.md, ja/api/configuration-build.md
This PR is document of https://github.com/nuxt/nuxt.js/pull/5635
=> Add ignoreNotFoundWarnings information to build doc

ja/.textlintrc, package-lock.json, package.json
I added `@textlint-rule/textlint-rule-no-invalid-control-character`
Please review it 🙇‍♂️
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/177
=> ja: Add @textlint-rule/textlint-rule-no-invalid-control-character

de/api/configuration-ignore.md, en/api/configuration-ignore.md, zh/api/configuration-ignore.md
=> en, de, zh: Fix ignore page path

ja/api/configuration-server.md
I updated `ja/api/configuration-server.md` .
Please review it 🙇
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/170
=> ja: Update configuration server

ja/api/configuration-router.md
I updated `ja/api/configuration-router.md`.
Please review it 🙇
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/169
=> ja: Update configuration router

ja/api/configuration-build.md
I updated ` ja/api/configuration-build.md`.
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/165
=> ja: Update configuration build

en/faq/deployment-azure-portal.md, en/faq/menu.json
+ add link to faq/deployment-azure-portal
+ change file extension to md.
=> en: update faq/deployment-azure-portal

ja/faq/heroku-deployment.md, ja/faq/netlify-deployment.md, ja/guide/async-data.md, ja/guide/directory-structure.md, ja/guide/index.md, ja/guide/installation.md, ja/guide/routing.md, ja/guide/views.md, ja/guide/vuex-store.md
resolve: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/132
=> ja: add video description

ja/api/configuration-servermiddleware.md
resolve: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/147
resolve: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/159
=> ja: update api/configuration-servermiddleware.md

ja/guide/plugins.md
未翻訳箇所を翻訳しました。お手すきの際にレビューよろしくお願いします
bot 稼働前までの本家との差分を埋めていこうと思います🌼
=> ja: update guide/plugin.md

ja/api/$nuxt.md, ja/api/menu.json
api/$nuxt.mdを追加しました。
一気にPRを出してすみませんが、お手すきの際にレビューよろしくお願いします
=> ja: add api/$nuxt.md

ja/examples/menu.json, ja/examples/typescript-vuex.md, ja/examples/typescript.md
TypeScript の例を追加しました。レビューよろしくお願いします
=> ja: add example/typescript.md and examples/typescript-vuex.md 

ja/faq/appengine-deployment.md
@inouetakuya @potato4d レビューよろしくお願いします。
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/162
=> ja: update faq/appengine-deployment

ja/api/configuration-server.md
=> ja: update api/confiuration-server

en/api/configuration-build.md
#1401 Pull request caused this issue.
=> fix: correctly rename cofiguration-build

ja/api/configuration-plugins.md
I updated `ja/api/configuration-plugins.md`.
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/176
=> ja: Update configuration plugins

ja/api/configuration-modern.md
I updated `ja/api/configuration-modern.md`.
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/168
=> ja: Update configuration modern

ja/api/context.md
I updated ja/api/context.md.
resolve vuejs-jp#172
=> ja: Update api/context.md

ja/api/pages-key.md
=> ja: fix typo

ja/api/configuration-generate.md
I updated ja/api/configuration-generate.md.
Please feel free to review it. thx.
resolve vuejs-jp#166
=> ja: Update ja/api/configuration-generate.md

ja/guide/contribution-guide.md
I updated ja/guide/contribution-guide.md.
resolve vuejs-jp#183
=> ja: Update guide/contribution-guide.md

ja/api/menu.json
resolve: [[doc] en: add missing in-page links to menu · Issue #185 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/185)
=> ja: Add missing in-page links to menu

README.md
=> Update primary maintainer for Japanese

ja/api/configuration-build.md, ja/api/configuration-render.md, ja/api/menu.json, ja/lang.json
I updated by version v2.8.0
resolve vuejs-jp#187
=> ja: Update version v2.8.0

en/guide/typescript.md
I just made the english sound a little more like the english language.
=> Update documentation for Typescript support

en/faq/deployment-azure-portal.md
ref: https://nuxtjs.org/faq/deployment-azure-portal
To display the code, I added language identifier.
=> en: add  language identifier to code blocks

en/faq/extend-webpack.md
Added a more elaborate description and example case of how to use the extend method of the build option for the `nuxt.config.js`. Having struggled with finding out how to use this API, I thought this might help future nuxt newbies. Happy to take any advice and make some adjustments! 🚀
=> en: `extend-webpack.md` with clearer explanation

ja/api/configuration-build.md
I updated api/configuration-build.md
resolve vuejs-jp#190
resolve vuejs-jp#188
=> ja: Update api/configuration-build.md

ja/guide/typescript.md
=> ja: fix guide/typescript.md

ja/faq/netlify-deployment.md
I updated ja/faq/netlify-deployment.md
resolve vuejs-jp#189
=> ja: Update faq/netlify-deployment.md

en/api/configuration-render.md
reflect changes in https://github.com/nuxt/nuxt.js/pull/5975
=>  en: update description for new render:csp option

en/faq/appengine-deployment.md
Add minimal yaml configuration for flexible enviroment.
=> en: Update appengine-deployment.md

ja/api/pages-transition.md
resolve: [[doc] en: update page transition details · Issue #197 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/197)
=> ja: update page transition details

ja/api/configuration-generate.md
resolve [[doc] en: improve configuration-generate explanation · Issue #196 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/196)
=> ja: improve configuration-generate explanation

zh/api/pages-transition.md
=> zh: update pages-transition.md

zh/guide/development-tools.md
=> zh: update development-tool.md

zh/api/components-nuxt.md
=> zh: Add and fix the nuxt module in the documentation

fr/faq/menu.json
This caused a fatal error: SyntaxError: Unexpected token {
=> Missed comma in JSON

de/api/configuration-router.md, en/api/configuration-router.md, es/api/configuration-router.md, fr/api/configuration-router.md, id/api/configuration-router.md, ja/api/configuration-router.md, ko/api/configuration-router.md, pt-BR/api/configuration-router.md, zh/api/configuration-router.md
Notice the documentation here was outdated. Used this as reference: https://raw.githubusercontent.com/nuxt/nuxt.js/918769ee9b2e73c3b8b67a434322235df995cedc/packages/vue-app/template/router.js
I went ahead and overwrote other languages even though the code comments are in English, since I assume when it comes to code snippets that accuracy is more important than being fully translated?
=> fix: update default scrollBehavior

en/api/configuration-generate.md
=> Add docs for generate.exclude

en/guide/installation.md
Hi. Thank you very much for an awesome framework :)
Some server-side & UI frameworks are not written on `installation.md`. Those frameworks added at following pull-requests.
* https://github.com/nuxt/create-nuxt-app/pull/111
* https://github.com/nuxt/create-nuxt-app/pull/186
* https://github.com/nuxt/create-nuxt-app/pull/162
Should I change other languages doc?
Thanks :)
=> docs(en): update server-side & UI framework list

fr/guide/installation.md, id/guide/installation.md, ja/guide/installation.md, zh/guide/installation.md
Some server-side & UI frameworks are not written on `installation.md`. Those frameworks added at following pull-requests.
* https://github.com/nuxt/create-nuxt-app/pull/111
* https://github.com/nuxt/create-nuxt-app/pull/186
* https://github.com/nuxt/create-nuxt-app/pull/162
English doc has already been updated #1476 
Thanks :)
=> docs(fr, id, ja, zh): update server-side & UI framework list

ja/api/configuration-router.md
Atinux-san resolved the matter that cannot be merged, so could you please check when you're available. (ref: https://github.com/nuxt/docs/pull/1477#issuecomment-513752084)
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/205
=> ja: update api/configuration-router

zh/api/menu.json, zh/api/pages-key.md, zh/guide/configuration.md, zh/guide/installation.md, zh/guide/routing.md, zh/lang.json
* add the key document in the api module is missing 
* instructions for missing documentation in the Guide module
* configuration document repair in the guide module
* routing document repair in the guide module
=> zh:  fix the documentation and add some documentation

en/faq/external-resources.md
&display=swap is added to the default url in Google Fonts
=> Add display=swap paramater

ja/guide/plugins.md
I updated guide/plugins.md
resolve vuejs-jp#208
=> ja: Update ja/guide/plugins.md

ja/guide/menu.json, ja/guide/upgrading.md
close: [[doc] chore: add upgrading to menu · Issue #212 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/212)
It is needed to translate ja/guide/upgrading.md in **another** PR. 😅
=> ja: chore: add upgrading to menu

en/api/configuration-modules.md, en/guide/menu.json, en/guide/modules.md
=> docs: buildModules

ja/api/configuration-generate.md, ja/api/menu.json
resolves https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/206, resolves https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/209
=> ja: update api/configuration-generator and menu

en/faq/cloudflare.md, en/faq/menu.json
Creates the cloudflare.md file, which contains instructions for properly setting up Cloudflare.
=> en: add cloudflare best practices

en/faq/netlify-deployment.md
In Netlify you can create a _redirects file with the rules as I have put and it is quite an easy way of making netlify work for page refreshes in spa mode
=> docs: add redirects file for netlify

en/api/pages-watchquery.md
Related to https://github.com/nuxt/nuxt.js/pull/6245
=> feat: function watchQuery

ja/guide/themes.md
resolves https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/242, resolves https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/240, resolves https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/239
=> ja: update guide/themes

en/api/configuration-router.md
=> en: fix scrollBehavior link

en/api/$nuxt.md
Some grammatical suggestions :)
=> en: grammar refinements in $nuxt.md

en/guide/views.md
Re https://github.com/nuxt/nuxt.js/pull/6374
=> docs: find app.html in src dir instead of root dir

en/guide/directory-structure.md
=> i.e. to e.g.

ja/faq/extend-webpack.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/255
=> ja: fix indentation

ja/api/components-client-only.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/252
> This branch is out-of-date with the base branch
sorry, I will update my branch.
=> ja: update api/components-client-only

zh/api/configuration-env.md
`import axios from '~plugins/axios'` 改为 `import axios from '~/plugins/axios'`
=> the file import url is not right

ja/guide/directory-structure.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/267
I fixed this issue. Please review it 😁
=> ja: update guide/directory-structure

ja/faq/deployment-aws-s3-cloudfront.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/264
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/265
I fixed these issues. Please review it 🙏
=> ja: update faq/deployment-aws-s3-cloudfront

ja/api/configuration-env.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/269
=> ja: update api/configuration-env.md

en/api/configuration-router.md, en/api/menu.json
https://github.com/nuxt/nuxt.js/pull/6331
=> en: document trailingSlash

en/api/context.md
Nothing fancy. I guess the section was just copied over.
=> Fixed typo

de/lang.json, en/lang.json, es/lang.json, fr/lang.json, id/lang.json, ja/lang.json, ko/lang.json, pt-BR/lang.json, ru/lang.json, zh/lang.json
Organized `lang.json` as part of the translation. Specifically, I removed keys and values ​​that are not imported by [nuxtjs.org](https://github.com/nuxt/nuxtjs.org). I have confirmed that there are no problems, but please confirm it just in case.
Ref: https://github.com/nuxt/nuxtjs.org/issues/263
=> Remove unused key and value from lang.json

ja/api/context.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/273
=> ja: update api/context

en/api/configuration-env.md
=> en: improve env example and wording

ja/lang.json
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/270
I fixed this issue. Please review it :octocat:
=> ja: update lang.json

ja/guide/commands.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/285
=> ja: update guide/commands

en/api/pages-head.md
Linking to page "external resources" in faq.
=> en: improve head documentation

fr/guide/views.md
Hi!
Noticed some typos while reading through the doc.
Have a nice day 😄
=> fr: Fix `views` typos

en/guide/typescript.md, fr/guide/typescript.md
- Update the french page
- Correct a small type in the EN page
=> [FR] update guide/typescript page

zh/guide/commands.md
According to the previous statement，I directly use 'npm run start'. But It reminds me to build first.So I would like to change the expression.
=> zh: fix commands.md

fr/guide/index.md
Fix the section title style so it's the same as the english one.
=> French Translation - Guide Index

fr/guide/menu.json
Fix the menu item link as it was still in english (application-monopage)
=> French Translation : Guide Menu

ja/api/internals-builder.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/296
=> ja: update internals/builder

ja/api/configuration-srcdir.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/294
I fixed this issue. Please review it 🏉
=> ja: update api/configuration-srcdir

ja/api/configuration-render.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/295
I fixed this issue. Please review it 🏉
=> ja: update api/configuration-render

ja/api/pages-head.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/292
I fixed this issue. Please review it 🌈
=> ja: update /api/pages-head

ja/api/configuration-build.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/297
=> ja: update api/configuration-build

en/api/configuration-render.md
add `addMeta` documentation (nuxt/docs#1655)
=> add `addMeta` documentation (nuxt/docs#1655)

en/api/configuration-extend-plugins.md, en/api/internals-builder.md, en/api/internals-module-container.md, en/api/menu.json
- fix #1628, adding extendPlugins docs
- fix internals builder build:prepare hook to builder:prepare
=> fix nuxt/docs#1628

de/faq/nginx-proxy.md, en/faq/laravel-forge-deployment.md, en/faq/nginx-proxy.md, fr/faq/nginx-proxy.md, ja/faq/laravel-forge-deployment.md, ko/faq/nginx-proxy.md, pt-BR/faq/nginx-proxy.md, zh/faq/nginx-proxy.md
=> fix English address typo

en/faq/nginx-proxy.md
=> Add necessary semicolon in nginx-proxy.md

en/api/menu.json
Fixes broken anchor links in the Configuration Loading and add missing links for Configuration LoadingIndicator menu items.
=> Fix: configuration loading & loadingIndicator menu

ja/api/components-nuxt-link.md, ja/api/configuration-router.md
resolve: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/279
=> ja: add prefetch prop to <nuxt-link>

ja/api/pages-watchquery.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/291
I fixed this issue. Please review it ☀️
=> ja: update api/pages-watchquery

ja/api/internals-builder.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/301
=> ja: update api/internals-builder

ja/api/configuration-extend-plugins.md, ja/api/internals-builder.md, ja/api/internals-module-container.md, ja/api/menu.json
I translated extendPlugins documents to Japanese.
resolve: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/309
=> ja: Translate extendPlugins docs

ja/api/configuration-cli.md
Resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/281
=> ja: add cli.bannerColor

fr/guide/contribution-guide.md
Comme proposer dans une précédente PR nous ne devons pas franciser je termes techniques les plus majoritairement utilisé. Mais plutôt s'habituer a utiliser les termes techniques générique ainsin demande d'amélioration devient naturellement pull request ou merge request
=> fr: Update contribution-guide.md

fr/guide/index.md
dans la partie ## Nuxt.js, qu’est-ce que c’est ?
J'ai voulu un peux mieux definir nuxt generate. Dites moi si je me trompe sur la definition. Aussi mettre les termes des trois modes (Meme si la definition du universal mode etait la je voulais juste le preciser)
Ainsi que corriger une faute
=> fr: Update index.md

fr/faq/host-port.md
Hi,
I've been trying to configure the port of my Nuxt app, then I noticed that there wasn't a french translation. Here is my contribution to this amazing project.
Thanks.
=> Translating Host Port In French

fr/api/menu.json, fr/examples/menu.json, fr/examples/typescript-vuex.md, fr/examples/typescript.md, fr/guide/menu.json
=> fr: move typescript docs to dedicated page

ja/api/configuration-env.md
I fixed a wrong link in `api/configuration-env.md`.
=> ja: fix link in api/configuration-env.md

ja/api/configuration-head.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/326
https://github.com/nuxt/docs/commit/cf4f820d5a057419c82a1c6132ff5bafc917d67f の差分を追加翻訳しました。
レビューお願い致します🙇‍
=> ja: Translate api/configuration-head.md

ja/lang.json
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/324
https://github.com/nuxt/docs/commit/b2e91bcbfa93b084e477ae09b15714a47caadc7d の差分に対応しました。
レビューお願い致します🙇‍
=> ja: Translate lang.json

ja/faq/webpack-plugins.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/320
https://github.com/nuxt/docs/commit/3045f240ef7e16b7ed7ea1e215d9aa55b091ab98 の差分を追加翻訳しました。
レビューお願い致します🙇‍
=> ja: Translate faq/webpack-plugins.md

ja/guide/modules.md
Correct subtle nuances in Japanese
=> ja: fix translation guide/modules.md

en/guide/directory-structure.md
=> fix(guide): Minor tweak

ja/faq/pre-processors.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/332
https://github.com/nuxt/docs/commit/0a8766f47ccf20523c88a4e7c0f330f02fe3bd21 の差分に追従させました。内容は、翻訳必要なかったです。
レビューお願い致します🙇‍
=> ja: Translate faq/pre-processors.md

en/api/pages-validate.md
Please check the accuracy of my information 😬
=> Add more info about the validate method

ko/guide/configuration.md, ko/guide/directory-structure.md, ko/guide/installation.md, ko/guide/routing.md, ko/guide/views.md
Hi!
I am going ahead on translation on the recent nuxt doc updates.
I am opening a PR from installation.md and more files are upcoming 😊
=> ko: Translate/update from installation.md ~

en/faq/now-deployment.md
by default you get 404 for service workers with default configuration.
=> add routes settings for now builder

ja/guide/vuex-store.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/341
サンプルコードの差分 https://github.com/nuxt/docs/commit/bdab5d18ca594c8a4787b899939c13f5fb144fff に対応しました。
レビューお願い致します🙇‍
=> ja: Translate guide/vuex-store.md

en/api/nuxt-render-route.md, en/api/nuxt-render.md, en/api/nuxt.md
Related work: https://github.com/nuxt/nuxt.js/pull/6868
=> feat: loadNuxt and build

en/blog/nuxtjs-from-terminal-to-browser.md, en/blog/nuxtjs-v240-is-out-typescript-smart-prefetching-and-more.md
@Atinux cherry-picked missing commit I had in local 65cd6035
=> improvement(post-authors): change author to authors + add more content

en/api/pages-fetch.md
Currently documentation doesn't provide visual example how to use fetchOnServer/fetchDelay options.
=> add fetchOnServer/fetchDelay example

en/homepage/modes_statically_generated.md
Change: ~~killing~~ => __kill__
=> Corrected a grammatical error in the Homepage

id/examples/seo-html-head.md, ko/examples/seo-html-head.md, ru/examples/seo-html-head.md, zh/examples/seo-html-head.md
closes #283
Fixing broken sandbox links
=> fix broken seo-html-head example links in multiple locales

en/homepage/modes_statically_generated.md
=> Grammar edits

en/guide/async-data.md
* Correct a grammatical mistake "of" -> "to"
* change "initiating" to "initializing" 
I'm new to Nuxt.js so I could be wrong here, thanks for reviews!
=> Grammar and word-usage change for async-data page

de/lang.json, en/blog/nuxtjs-from-terminal-to-browser.md, en/blog/nuxtjs-v240-is-out-typescript-smart-prefetching-and-more.md, en/lang.json, es/lang.json, fr/lang.json, id/lang.json, ja/lang.json, ko/lang.json, pt-BR/lang.json, ru/lang.json, zh/lang.json
Add Blog to headerLinks and add example blogpost image in static for Cloudinary
=> feat: blog update

en/blog/understanding-how-fetch-works-in-nuxt-2-12.md
- **What's next** section added
- Code-block indented properly
- Proper titles added to five differences towards the end
- HTTP status code paragraph added
- HTTP status code paragraph moved up with main Error Handling section
=> What's next section added and Error Handling section amended

en/blog/understanding-how-fetch-works-in-nuxt-2-12.md
Removed all five occurrence of `page redirection` in reference to custom error page to avoid confusion
=> Blog post/new fetch update v2

en/api/configuration-build.md
- Change `conditionnaly` to `conditionally`
=> en: fix spelling for transpile section

en/api/internals-builder.md
Spent hours finding out about this hope this fix will save someone else's time
=> en: fix hook name

fr/api/configuration-global-name.md, fr/api/configuration-render.md, fr/api/configuration-rootdir.md, fr/api/configuration-router.md, fr/api/configuration-server.md, fr/api/configuration-servermiddleware.md, fr/api/configuration-srcdir.md, fr/api/configuration-transition.md, fr/api/configuration-vue-config.md, fr/api/configuration-watch.md, fr/api/configuration-watchers.md, fr/api/menu.json, fr/guide/modules.md
Page translated : 
- fr/api/configuration-global-name.md
- fr/api/configuration-render.md
- fr/api/configuration-rootdir.md 
- fr/api/configuration-router.md
- fr/api/configuration-server.md 
- fr/api/configuration-servermiddleware.md
- fr/api/configuration-srcdir.md
- fr/api/configuration-transition.md 
- fr/api/configuration-vue-config.md 
- fr/api/configuration-watch.md 
- fr/api/configuration-watchers.md 
+ update api title menu 
- fr/api/menu.json
=> fr: latest configuration pages

en/api/internals-module-container.md
Changed "dist" to "dst" as this is the actual property being returned.
=> Change "dist" to "dst"

en/api/configuration-loading-indicator.md
add loadingIndicator property to example to make it easier to understand
=> en: add loadingIndicator property

ja/api/internals-module-container.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/392
Hi! 
Please review this PR.
=> ja: fix: dist to dst

en/api/pages-watchquery.md
This is to resolve issue [7281](https://github.com/nuxt/nuxt.js/issues/7281)
=> en: add clarification around watchQuery and the new fetch hook

ja/guide/routing.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/398
こんばんは、レビューをお願いします！
翻訳に挑戦するのは初めてなのでおかしなところがあれば指摘してください🙏
=> ja: Translate guide/routing extending the router

en/faq/appengine-deployment.md
please improve wordings if required. but I think `start` should be mentioned explicitly.
=> highlighting `start` command

de/api/configuration-build.md, en/api/configuration-build.md, es/api/configuration-build.md, fr/api/configuration-build.md, id/api/configuration-build.md, ja/api/configuration-build.md, ko/api/configuration-build.md, pt-BR/api/configuration-build.md, ru/api/configuration-build.md, zh/api/configuration-build.md
This is an apparent error in description
=> [Build] followSymlinks: false -> true

en/faq/pre-processors.md
This example in our docs doesn't work so removing it
=> docs: remove coffee script

ja/faq/pre-processors.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/406
レビューをお願いします！
=> ja: docs: remove coffee script

en/blog/going-dark-with-nuxtjs-color-mode.md
remove paragraph that shouldn't be there
=> blog: remove wrong paragraph

en/guide/vuex-store.md
This example was missing part of the remove method. Also change to use filter and added unique id
=> docs: improve store example

ja/api/configuration-loading-indicator.md
@inouetakuya  @aytdm  @53able 
loadingIndicatorが記載漏れしています。
https://ja.nuxtjs.org/api/configuration-loading-indicator/
=> ja: Add missing code documentation

ja/api/configuration-server.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/385
=> ja: added server/index.js config

ja/guide/installation.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/403
=> ja: Add Vuesax link

ja/guide/async-data.md
fix https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/411
=> ja: remove gone blog post link

ja/api/configuration-router.md
resolve resolve vuejs-jp#402
948cc22 の差分に対応しました。
ご確認お願い致します🙇‍
=> ja: Translate api/configuration-router.md

ja/api/internals-generator.md
resolve resolve vuejs-jp#395
cb15726 の差分を転機しました。
ご確認お願い致します🙇‍
=> ja: Translate api/internals-generator.md

ja/faq/http-proxy.md
@inouetakuya @53able I appreciate for your confirmation when you're available.
resolve: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/361
=> ja: remove -D option

ja/guide/modules.md
@inouetakuya @53able I appreciate for your confirmation when you're available.
resolve: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/354
=> ja: add translation guide/modules

ko/api/configuration-servermiddleware.md
=> ko: fix typos

en/api/configuration-loading-indicator.md, en/guide/index.md
Added definite article `the` to clarify sentence
=> en: Small Typo Fix

ja/faq/pre-processors.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/376
en commit id: 02c01172a6b050c7e63b168ccd73994b928b607d
Sorry for the delay :bow: :bow:
=> ja: Translate don't pin pug dep

ja/faq/deployment-azure-static-web-apps.md, ja/faq/menu.json
resolve vuejs-jp#408
77111a9 の差分を追加翻訳しました。
レビューお願い致します🙇‍
=> ja: Translate faq/deployment-azure-static-web-apps.md

ja/api/components-nuxt.md
resolve vuejs-jp#420
84a39b0 の差分を追加しました。
レビューお願い致します🙇‍
=> ja: Translate api/components-nuxt.md

en/faq/menu.json
issue: https://cmty.app/nuxt/docs/issues/c262
(I was not able to use cmty => not possible to specify a version after selecting Bug report- Firefox 77.0.1 64bits ; Ubuntu 18.4.4 LTS)
=> ko: deploy PM2

ja/faq/now-deployment.md
@inouetakuya @aytdm @53able 
I need to review this request 🙇‍♂️ 
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/428
=> ja:Update now-deployment to match new company name

ja/homepage/welcome.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/405
en commit id: 7d6cdf444a69f3d377ddd4e2417d28031892a6d6
=> ja: Translate welcome title

en/blog/going-full-static.md
=> fix: remove empty videos

en/api/configuration-runtime-config.md
in addition highlights crucial parts in bold.
=> en: fixes description on 'privateRuntimeConfig'

en/guide/index.md
=> Fixed grammar and spelling a wee bit

en/api/configuration-build.md, en/api/configuration-modern.md, en/api/configuration-render.md, fr/api/configuration-modern.md, ja/api/configuration-modern.md, ko/api/configuration-modern.md, zh/api/configuration-modern.md
changes based on https://github.com/nuxt/nuxt.js/pull/7187 (Move build.crossorigin to render.crossorigin)
=> docs: move crossorigin to render configuration

ja/api/pages-fetch.md
resolve vuejs-jp#421
c104375 の差分を追加翻訳しました。
レビューお願い致します🙇‍
=> ja: Translate api/pages-fetch.md

ja/api/internals-renderer.md
resolve vuejs-jp#427
8434493 の差分に対応しました。
レビューお願い致します🙇‍
=> ja: Translate api/internals-renderer.md

ja/api/components-nuxt-child.md
@inouetakuya @53able
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/430
Original: nuxt@d501b66
=> ja: Inform about activated and deactivated hooks

ja/homepage/welcome.md
@inouetakuya @53able 
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/459
Original: nuxt@b1f4063
=> ja: add cta for newsletter

ja/api/configuration-build.md, ja/api/configuration-render.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/456
en commit id: https://github.com/nuxt/docs/commit/d4528b162130a241a0ce7749ca3a3cc7dd041612
=> ja: move crossorigin to render configuration
