- en/guide/development-tools.md
I made a few small grammar and typo changes to the 'jsdom limitations' section just above the ESLint section.
> Small grammar and typo fixes on en/guide/development-tools page

- cn/guide/development-tools.md
- en/guide/development-tools.md
Adds documentation to ava end to end tests to transpile imported files with babel.  
https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md
Note: This still does not have recommendation on how to transpile .vue files that are imported outside of nuxt page tests
> Add documentation to have ava transpile imported files

- en/api/configuration-dev.md
- en/examples/auth-routes.md
- ru/examples/auth-routes.md
I wasn't sure what protocol to follow regarding translations.. I didn't add anything to the cn translation pages since they'd already been translated. I changed one file in the ru translation but the other file(api/configuration-dev.md) seemed to be missing there? Just let me know if I need to adjust my PR.
> Make start scripts in examples Windows-friendly

- jp/guide/index.md
> fix typo in Japanese translation

- en/faq/github-pages.md
- en/guide/assets.md
I saw the question about handling the CNAME file for GitHub Pages yesterday in Japanese Vue.js community. I think it is useful to add the documentation about it.
> Add the documentation about CNAME file for GitHub Pages

- en/faq/github-pages.md
- jp/faq/github-pages.md
- jp/guide/assets.md
I have moved the documentation about CNAME file out of command line deployment because CNAME file has little relevance with command.
Then I have reflect the update of #68 to Japanese translation.
> Reflect the update of #68 to Japanese translation

- en/faq/google-analytics.md
When using this snippet from the FAQ, I came across linting errors.
The best way for me to resolve this was to add `/* eslint-disable */` at the beginning; it makes no sense rewrite the GA part to match our linting config, and since we use .gitignore as the source for files to ignore in the `package.json` *lint* script we can't create an .eslintignore file.
> Disable Eslint for the Google Analytics snippet

- jp/api/configuration-build.md
- jp/api/configuration-cache.md
- jp/api/configuration-css.md
- jp/api/configuration-generate.md
- jp/api/configuration-head.md
- jp/api/configuration-plugins.md
- jp/api/configuration-router.md
- jp/api/menu.json
- jp/api/pages-transition.md
- jp/faq/google-analytics.md
- jp/guide/plugins.md
- jp/guide/views.md
I have reflected "Update doc for 0.10 · nuxt/docs@11d0be2" to Japanese translation.
> Reflect "Update doc for 0.10 · nuxt/docs@11d0be2" to Japanese translation

- cn/api/configuration-watchers.md
- en/api/configuration-watchers.md
- jp/api/configuration-css.md
- jp/api/configuration-watchers.md
- jp/api/menu.json
- ko/api/configuration-watchers.md
I have reflected "add watchers doc · nuxt/docs@640e03a" to Japanese translation.
> Add watchers doc to Japanese translation

- jp/api/nuxt-render-route.md
I have reflected "Fix broken link on nuxt-render-route page" #66 to Japanese translation.
> Reflect "Fix broken link on nuxt-render-route page" #66 to Japanese translation

- README.md
Revert nuxt/docs#67 
This revert is related to the issue: [Why are some translation directory names using Country Code instead of Language Code ? · Issue #92 · nuxt/docs](https://github.com/nuxt/docs/issues/92)
> Revert "Reflect the update of Japanese translation repository name"

- en/guide/async-data.md
Before it was unclear how to reference dynamic route data. The examples used `slug` and `id` which seemed like generic names for different route param data. So my routes appeared to not be updating, only because I was using `params.slug` when my file was named `_lesson.vue`, so I should have been using `params.lesson` to access the data.
> specified how to access dynamic route data with asyncData property

- en/guide/vuex-store.md
- ja/guide/vuex-store.md
- ko/guide/vuex-store.md
- zh/guide/vuex-store.md
The current code will work, but `delete` is a reserved word in JavaScript. I think it's better to change to something like `remove` so it's less confusing. This will also fix the syntax highlighting on the nuxt website.
> Use remove instead of delete

- en/guide/vuex-store.md
I had some debugging pain a couple of days ago using `nuxtServerInit` with a callback-style async action.   Eventually I realized that it must return a Promise for anything async so that the nuxt server can wait on it properly.  A quick note in the docs should help others avoid that same mistake.
Feel free to change the wording & formatting to fit your preferred style!
> Add note that async nuxtServerInit must be promise

- ja/api/configuration-router.md
original is https://github.com/nuxt/docs/blob/master/en/api/configuration-router.md
```
- Type: `String`
- Default: `'nuxt-link-exact-active'`
Globally configure [`<nuxt-link>`](/api/components-nuxt-link) default exact active class.
Example (`nuxt.config.js`):
\`\`\`js
module.exports = {
router: {
linkExactActiveClass: 'exact-active-link'
}
}
\`\`\`
> This option is given directly to the [vue-router Router constructor](https://router.vuejs.org/en/api/options.html).
```
cc:/ @inouetakuya
> Translate linkExactActiveClass of configuration-router into Japanese

- en/guide/vuex-store.md
Update the docs to reflect that the store now needs to be exported as a function
> Vuex store

- README.md
- package.json
It is requied at least `node >= 7.6.0` to start the server because supporting async/await is needed.
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#7.6.0
> update V8 to 5.5 (Michaël Zasso) #11029
(V8 5.5 supports async/await)
ref. [Node 7.6 Brings Default Async/Await Support](https://www.infoq.com/news/2017/02/node-76-async-await)
```
$ node -v
v7.5.0
$ npm run dev
> nuxt-docs@1.0.0 dev /Users/inouetakuya/src/github.com/inouetakuya/ja.docs.nuxtjs
> nodemon --watch *.js --exec 'node api.js'
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: api.js
[nodemon] starting `node api.js gh-hook.js`
/Users/inouetakuya/src/github.com/inouetakuya/ja.docs.nuxtjs/api.js:37
async function getReleases () {
^^^^^^^^
SyntaxError: Unexpected token …
```
> It is requied at least `node >= 7.6.0` to start the server

- en/faq/google-analytics.md
- ja/faq/google-analytics.md
- ko/faq/google-analytics.md
- zh/faq/google-analytics.md
As @pi0 [pointed out](https://github.com/nuxt/nuxt.js/issues/792#issuecomment-304327304), importing `router` from `~router` does not work. However, that's what [the official documentation](https://nuxtjs.org/faq/google-analytics) suggests.
This can lead many users(me 10 mins ago, for example) to confusion. So I fixed this.
I can confirm that Korean & English version's comments make sense as I'm Korean. However, I don't speak Japaneses and Chinese so I just copied the comments which were originally there. Also, for the same reason, I didn't make this change in, for example, russian docs as there weren't this page at all in the first place.
> Fix FAQ regarding google analytics

- en/api/configuration-css.md
Hello there :)
Loading css files from current directory requires ```node-sass``` and ```sass-loader``` but it's not stated in the documentation. Same issue here also: nuxt/nuxt.js#1003
Hope it helps
> Provides more information to avoid nuxt/nuxt.js#1003

- en/guide/vuex-store.md
Hi,
this is to avoid confusion about the Vuex store plugins when the store is used in Modules Mode (see https://github.com/nuxt/nuxt.js/issues/560).
Awesome Nuxt!
All the best.
Marcello
> How to use Vuex plugins in Modules Mode

- README.md
Updated the readme to state that the main nuxt.js website report must also be running on localhost:3000 for the docs to be accessed. re #184
> Updated readme with dev info

- en/guide/directory-structure.md
'rooDir' corrected to 'rootDir'
> Fix small typo

- en/guide/vuex-store.md
See https://nuxtjs.org/examples/vuex-store for a working example
Using the example in https://nuxtjs.org/guide/vuex-store I got this error:
> [nuxt] store/index.js should export a method which returns a Vuex instance.
> Up to date api for vuex store

- en/guide/development-tools.md
- es/guide/development-tools.md
- fr/guide/development-tools.md
- ja/guide/development-tools.md
- ko/guide/development-tools.md
- ru/guide/unit-testing.md
- zh/guide/development-tools.md
Hey,
this updates the end-to-end testing doc with the current Nuxt API. 
I also updated the comments in the code, but only for the english version as I don't speak any of the other languages. So I would need help there.
I noticed that in the Russian guide the docs are in `unit-testing.md` instead of `development-tools` resulting in a 404 [here](https://ru.nuxtjs.org/guide/development-tools/). This is certainly not unit testing is it? I can't read Russian though, so I don't know what it says in that file. So again, help needed!
> Update Testing Documentation

- en/api/nuxt-render.md
This seems to make more sense.
If this is the first time running the app, not in dev mode, and `.nuxt/` does not yet exists, will the app be able to function if it is not built? Is there a non-dev-mode build that should be first called?
> listen after done building.

- en/guide/plugins.md
> [Doc EN]: `guide/plugins.md`

- en/guide/assets.md
> [Doc EN]: `guide/assets.md`

- en/guide/async-data.md
> [Doc EN]: `guide/async-data.md`

- en/guide/routing.md
> [Doc EN]: `guide/routing.md` review

- en/guide/configuration.md
> [Doc EN]: `guide/configuration.md` review

- en/guide/development-tools.md
> [Doc EN]: `development-tools.md` review.

- en/guide/modules.md
> [Doc EN]: `modules.md` review.

- ja/faq/window-document-undefined.md
refs https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc3
> process.BROWSER_BUILD is changed to process.browser

- fr/api/index.md
Hi @Atinux, because the name file of asyncData is `index.htm` we have forgotten to add it amongs translated pages :)
This is the correction of that !
> [Doc FR]: `asyncData` in french

- en/api/configuration-servermiddleware.md
- fr/api/configuration-servermiddleware.md
The github.com urls to the express-template in the server middleware documentation were relative.
Both En & Fr are fixed, other languages didn't seem affected with this issue or didn't have the documentation for server middleware configuration.
> Fix relative github.com anchors

- en/guide/configuration.md
Remove `cache` listing from configuration documentation.
This feature was deprecated, and corresponding documentation, that this leads to, is gone.
> Remove deprecated `cache` documentation

- en/examples/cached-components.md
This feature was deprecated, and corresponding documentation, that this leads to, is gone.
This example is currently misleading and should be deleted.
It would probably be a great idea to provide a replacement entry in FAQ page. Leading to [@nuxtjs/component-cache](https://github.com/nuxt-community/modules/tree/master/packages/component-cache)
> Delete cached components example

- en/api/menu.json
- fr/api/menu.json
The _hotMiddleware_ link in the API menu does not point to the right anchor in EN and FR.
> Fix hotMiddleware menu link

- en/faq/pre-processors.md
At the first glance (for beginners), it's not clear if `lang="sass"` would work with scss as well and this throws css errors.
IMO, it makes sense to add a scss lang snippet, to reflect that it should work with scss syntax as well, if you set `lang`. Opinions?
> Added scss code snippet

- en/faq/github-pages.md
- en/guide/commands.md
- en/guide/index.md
Raised from issue https://github.com/nuxt/nuxtjs.org/issues/92
Documentation for deploying to GitHub Pages for repository site, to make sure users can deploy correctly
> Adding GitHub Pages base router documentation

- README.md
This pull request fixes a typo (useing => using) and splits the sentence into two smaller sentences.
> Fix typo and rephrase the sentence about translation in README.md

- en/guide/development-tools.md
- es/guide/development-tools.md
- fr/guide/development-tools.md
- ja/guide/development-tools.md
- ko/guide/development-tools.md
- zh/guide/development-tools.md
Following the instructions in the [documentation](https://github.com/nuxt/docs/blob/d48dadc3387b6a60b636faa060d9a0cad2d7a28c/en/guide/development-tools.md#eslint) to add ESLint I encountered the following errors:
```
Oops! Something went wrong! :(
ESLint: 4.15.0.
ESLint couldn't find the plugin "eslint-plugin-import". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make sure eslint-plugin-import is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
npm i eslint-plugin-import@latest --save-dev
If you still can't figure out the problem, please stop by …
```
> Add `eslint-plugin-import` & `eslint-plugin-node` to ESLint docs

- en/api/pages-fetch.md
Added missing edge case to `fetch` usage with Vuex `dispatch`. If this is not done when using Vuex with Nuxt, then the Component `fetch` method will not trigger on page refresh.
If I am in any way incorrect, please correct me in possible alternatives. In my own experience, using `fetch` will not work otherwise.
Is this intentional functionality? If so it should be documented. Otherwise, if this is not intentional, then there is something much deeper that needs to be fixed.
This was also discussed previously: https://github.com/nuxt/nuxt.js/issues/1852
> Documented Fetch Use With Vuex

- en/api/components-no-ssr.md
- en/api/menu.json
Nuxt include a `<no-ssr>` component, but documentation about it does not exist.
So, I added to documentation it.
The quoting source for `<no-ssr>` seems to be `egoist/vue-no-ssr`.
Should I add reference to it? Just like `<nuxt-link>` 's document.
> Add <no-ssr> component document (Only /en)

- en/api/nuxt-render-and-get-window.md
Currently on the site, when you click on the 'test purposes' link, it takes you to a page that doesn't exist, as the path is relative. This fixes the link by making it absolute, like the link found on the nuxt.renderRoute page. (https://nuxtjs.org/api/nuxt-render-route)
> Fix link to end-to-end testing section

- es/guide/development-tools.md
Given setup is quite outdated and am not sure if even works. Eslint works much better with `eslint-plugin-vue` and `prettier`. Not only this allows to report ,most of the issues, but also to fix them
This setup also nicely plays with code editors and VS code in particular.
> Updated recommended eslint config

- ja/api/nuxt-render.md
Error: Nuxt is not a constructor
古いコードだとのエラーがでるので、こちらの最新版のコードにあわせた。
https://github.com/nuxt/nuxt.js/blob/master/examples/custom-server/server.js
> nuxt-render を最新のサンプルコードに更新

- en/api/configuration-build.md
The link to the webpack-bundle-analyzer git was missing an **r** at the end.
> Fixed webpack-bundle-analyzer link

- id/api/context.md
There are a conflict issue on Indonesian Translation at api/context file.
This PR solve that by fixing broken markdown's table format.
cc @tapitapeh
> Fix broken table format on api/context ID translation - ID

- en/guide/development-tools.md
Since Nuxt is now using `env` babel preset, the configuration for testing should reflect this change
> Change babel preset to `env`

- en/faq/external-resources.md
I think it should use the `head` method.
```diff
- head: {
-   ...
- }
+ head () {
+   return {
+     ...
+  }
+ }
```
> Fix external resources example code

- en/faq/pre-processors.md
vue-loader v15+ uses pug-plain-loader instead of pug-loader.
https://github.com/yyx990803/pug-plain-loader
> Correct pug dependency

- en/faq/dokku-deployment.md
When following the guide on dokku deployment I missed the specification how to run the final process that launches the actual application. When this is not set it fails with a message similar to (depending on your current Procfile content):
```
Cannot find module '/app/dist'
```
This is solved by specifying which command should be run on the dokku deploy.
> Update dokku deployment

- en/api/configuration-ignore.md
- en/api/configuration-modules.md
- en/api/menu.json
Fixes https://github.com/nuxt/nuxt.js/issues/3631
- Added link to `/configuration-ignore` to API menu
- Rewrote text for clarity and consistency with other pages.
- Removed inconsistent emphasis in title of modules page.
> Add ignorePrefix to API menu

- en/api/configuration-modulesdir.md
- en/guide/configuration.md
Issue: #702
Changes:
- Section added to `en/guide/configuration.md`, including link to API section
- `en/api/configuration-modulesdir.md` reformatted to be consistent with other API sections and include an example
> Info on modulesDir configuration option missing from documentation

- en/guide/development-tools.md
"End to End Testing" tutorial does't work When using spa mode because spa mode does't make page content.
To avoid that, set to universal mode in `test.before`.
> declare config.mode as universal.

- de/guide/modules.md
- en/guide/modules.md
- fr/guide/modules.md
- ja/guide/modules.md
- pt-BR/guide/modules.md
`base.config.js` is renamed to `base.js`
https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/base.js
> update webpack config file path

- ja/guide/views.md
@inouetakuya @potato4d  @aytdm 
`ja/guide/views.md` の ページ：loadingを追加しました。
https://gitlocalize.com/repo/100/ja/en/guide/views.md
> `false` に設定すると、入力したページが自動的に `this.$nuxt.$loading.finish()` を呼び出すのを防ぎ、`this.$nuxt.$loading.start()` を使用して動作を 手動で制御できます、[example](/examples/custom-page-loading)を参照してください。
* 意味合いは間違っていないか?
* 長くなりすぎていないか(途中で句点(。)を入れたほうが良いか?)
見ていただけると嬉しいです。
訳の意味合いについて自信がなかったので、候補として他のも考えてみました。
> `false` に設定すると、ページから自動的に `this.$nuxt.$loading.finish()` と `this.$nuxt.$loading.start()` が呼び出されるのを防ぎます、この手動で制御する動作は[example](/examples/custom-page-loading)から確認できます。
以上、レビューお願いします! :pray:
> ja: Update ja/guide/views.md

- api.js
github dont guarantee order of releases in their api.
> sort releases by published date

- en/api/configuration-modulesdir.md
Hi. nuxt/docs authors.
I found a page with a slightly broken layout so I fixed it.
Display of "Example:" etc. is different from other pages.
via. https://nuxtjs.org/api/configuration-modulesdir
Please feel free to review it.
Thanks :)
> Fix text layout: en/api/configuration-modulesdir.md

- zh/guide/index.md
- zh/lang.json
I am very pleased that nuxt.js has released version 2.0, which makes nuxt.js better optimized and experienced in its use.
There are more and more Chinese developers using nuxt.js. They are troubled by the lack of Chinese documents, so I translated some Chinese documents and translated them with the nuxt.js2.0 English documents. If I can approve these, I will use the remaining time to continue. Translation, as a contributor to nuxt.js, I feel very honored, thank you!
> Update Chinese document (introduction) to synchronize with nuxt2.0 English document

- en/examples/auth-external-jwt.md
- en/examples/auth-routes.md
- en/guide/vuex-store.md
To avoid shared state on the server side (which results in unwanted "caching") we should change our state assignments to `functions` everywhere.
Related: [this](https://stackoverflow.com/questions/49557177/vuex-state-returned-as-function-or-object-literal) SO thread
> fix(vuex): rewrite state to functions everywhere

- en/guide/vuex-store.md
Tried to keep the hint as short as possible let me know if you want me to remove a few lines! I placed is under Module Files sections as I felt it would be at this point that most people would run into issues with not having access to ```this``` because of using arrow functions.
Resolves #849
> Doc Update: Added hint as to why arrow functions don't have there own 'this'

- de/api/menu.json
- en/api/menu.json
- fr/api/menu.json
- id/api/menu.json
- ja/api/menu.json
- pt-BR/api/menu.json
API menu update for the `en` lang:
- Add `dist` to `configuration-render`
- Swtich `gzip` for `compressor` in `configuration-render`
API menu update for the `en`, `de`, and `fr` langs:
- Add `static` and `csp` to `configuration-render`
API menu update for the `en`, `de`, `fr`, `id`, `ja`, and `pt-BR` langs:
- Match the page's generated anchor for `bundleRenderer` and `resourceHints`
> Fix the API menu to match content (en, de, fr, id, ja, pt-BR langs)

- ja/api/internals-builder.md
遅くなってすみません。
ja/api/internals-builder.md を翻訳しました。
レビューよろしくお願いします！ 🙏
en: https://github.com/resessh/nuxt-docs/blob/master/en/api/internals-builder.md
master の更新分を取り込んでます。
> ja: Update ja/api/internal-builder.md

- en/faq/nginx-proxy.md
Added an advanced nginx example for when you use Nuxt to generate all (dynamic) routes of your project so nginx can serve mostly static files. But I also added a caching proxy to a Nuxt server so if an url is not (yet) generated the Nuxt server will generate the page for that url and nginx will cache it until its invalidated or purged.
The example doesnt explain how everything works, its more to show what is possible and if you want to know exactly how and why then you should RTFM (of nginx mostly)
> feat: add advanced nginx example

- .gitignore
- api.js
- package.json
fix: add yarn-error to gitignore
This will make it much easier to link to a certain section of the docs. See also https://github.com/nuxt/nuxtjs.org/pull/159 for the required styles.
--edit--
Forgot to say, the anchor links dont work on `h1` because they have an `overflow: hidden`.
> feat: add github-like anchors to headers

- ja/api/configuration-loading-indicator.md
Resolves #912 
> ### What problem does this feature solve?
> 
> The problem is on the following page!
> 
> https://ja.nuxtjs.org/api/configuration-loading-indicator/
> 
> #### 1. Currently, there is a typographical error in markdown notation, and the appropriate text is not linked.
> 
> If this problem is solved, the user can access the appropriate link.
> 
> #### 2. Currently, accessing the set link will return 404 error.
> 
> If this problem is solved, the user can access the appropriate link.
> 
> 
> ### What does the proposed changes look like?
> 
> Line 48, `/docs/ja/api/configuration-loading-indicator.md `
> 
> #### before
> 
> ```markdown
> 
> ベースが必要な場合は、 Nuxt の組み込み[ソースコード]((https://github.com/nuxt/nuxt.js/tree/dev/lib/app/views/loading)をベースとして使用できます。
> ```
> 
> #### after
> 
> …
> In the Japanese document, There is a misprint on the page of "LoadingIndicator property".

- en/guide/configuration.md
Add 'is' to correct the English.
> Correct grammar for env

- en/guide/routing.md
Explain that middleware only get executed once and from server when page reload
> Update middleware doc

- fr/guide/plugins.md
Replaces `store` by `app` in context params and removes useless `inject` argument
> Fix plugins/i18n.js section

- de/api/configuration-vue-config.md
- en/api/configuration-vue-config.md
- fr/api/configuration-vue-config.md
- ja/api/configuration-vue-config.md
- zh/api/configuration-vue-config.md
Update `productTip` to `productionTip`. 
I think it's a typo as `productTip` doesn't look like it's a vue.config option.
> vue.config change productTip for productionTip

- zh/guide/modules.md
[mistake page](https://zh.nuxtjs.org/guide/modules)
参考 莫模块配置 文档来查看更多”  这里有个错别字
莫模块配置 错别字
> Chinese Doc has a character mistake

- en/guide/routing.md
There was a feature built in to NuxtJS that my team had difficulty discovering in the docs.
We had a dynamic structure for our URLs, provided by our CMS platform. This allowed users to create pages on their own like this:
* `/about`
* `/careers`
* `/careers/culture`
* `/careers/locations`
We we're hoping all these routes could match one "General Content Page" view in our Nuxt app! 
For our initial attempt, we ended up hijacking the NuxtJS routes in a very strange and complex way to handle these custom routes.
Fortunately, I came across this [Stack Overflow solution](https://stackoverflow.com/questions/49951479/infinite-dynamic-level-nesting-in-nuxt-js) which told me the "Nuxt way" to handle this use case.
I hope this addition to the Routing documentation helps others who encounter the …
> add documentation for unknown route depth

- ja/guide/modules.md
guide/modules.md の Alert 内の `[Nuxt Internals]` リンクが外れていたので Alertクラスのタグと改行を修正し正しくリンクされるようにしました。
> ja: fix guide/modules.md

- en/api/menu.json
Just a quick update to add some missing menu items 🏷
> Add parseQuery, stringifyQuery, and fallback items to router submenu

- en/guide/async-data.md
Updated docs as the callback-based asyncData, fetch or middleware calls are deprecated since 2.3.1.
> Update asyncData docs

- ja/guide/menu.json
https://github.com/nuxt/docs/commit/549a7c296eae7db14b4db59b8b28a1f8d95a5e9a
でリンク先が変わっているので、リンク切れになっていました。
nuxt/docsのPRの作法として間違ってたら申し訳ないです 🙇
> ja: Fix broken link

- en/api/configuration-build.md
- en/api/context.md
Add short warning note about `isClient`/`isServer` in build extend to deter developers from thinking it is deprecated and should be replaced with `process.client`/`process.server`, which would return undefined and therefore cannot be used.
There appearrs to be a large amount of misinformation about this property, leading to a lot of incorrect configurations that *appear* to be correct because replacing `isClient` with `process.client` will disable linting, making it appear as if there are no errors, when the reality is they have just disabled linting.
> Add warning note about isClient and isServer

- ja/guide/commands.md
Hi!
I found some broken markdown layout on `ja/guide/commands.md` file, so I fixed it correctly.
> ja: Fix some broken md formt on JP guide.

- de/faq/window-document-undefined.md
- en/faq/window-document-undefined.md
- es/faq/window-document-undefined.md
- fr/faq/window-document-undefined.md
- id/faq/window-document-undefined.md
- ja/faq/window-document-undefined.md
- ko/faq/window-document-undefined.md
- pt-BR/faq/window-document-undefined.md
- ru/examples/plugins.md
- ru/guide/plugins.md
- zh/faq/google-analytics.md
- zh/faq/window-document-undefined.md
`process.BROWSER_BUILD` was removed in release v1.0, so now the docs are incorrect.
> Replace process.BROWSER_BUILD and process.browser with process.client

- en/api/configuration-loading.md
Corrected typo on both the start() and finish() method descriptions on custom loading components, removed the *here* preceeding *where*. So it would now reads: *Called when a route changes, this is where you display your component* instead of: Called when a route changes, this is *here* where you display your component.
> Corrected a typo on custom loading component

- en/guide/plugins.md
- zh/api/configuration-build.md
- zh/api/configuration-modern.md
Update Chinese document：auto-detect mode and crossorigin
Fix the description of the error
😸
> Update Chinese document：auto-detect mode and crossorigin

- en/api/internals-builder.md
The obj that's passed to build:templates hook actually has the prop templatesFiles not templateFiles
> updated build:templates args

- en/faq/now-deployment.md
Current docs are describing how to setup deployment for Now V1, while it's already a legacy version and it doesn't work anymore on Now V2.
For now, I omitted the part of setting up the deployment of a universal app with SSR, because still need to figure out how to do it.
> ZEIT Now deployment configuration update

- en/api/configuration-build.md
Add additional clarification detailing the use of build.transpile.
It was not clear that the string could be the name of the package to transpile.
> build.transpile usage clarification

- en/api/configuration-build.md
Babelrc usage is turned off by default. No info about it in documentations and that is very confusing.
Update docs according to code here: https://github.com/nuxt/nuxt.js/blob/2.x/packages/config/src/config/build.js#L68
> Update build.babel block

- de/api/configuration-dev.md
- de/api/nuxt-render.md
- en/api/configuration-dev.md
- en/api/nuxt-render.md
- es/api/configuration-dev.md
- es/api/nuxt-render.md
- fr/api/configuration-dev.md
- fr/api/nuxt-render.md
- id/api/configuration-dev.md
- id/api/nuxt-render.md
- ja/api/configuration-dev.md
- ja/api/nuxt-render.md
- ko/api/configuration-dev.md
- ko/api/nuxt-render.md
- pt-BR/api/configuration-dev.md
- pt-BR/api/nuxt-render.md
- zh/api/configuration-dev.md
- zh/api/nuxt-render.md
remove nuxt.showOpen()
&
let nodejs handle error
(dumb me messed up last pull request :/)
> Replace `nuxt.showOpen` with `nuxt.showReady`

- ja/guide/directory-structure.md
supplement missing slash in path.
> Fix typo in ja/guide/directory-structure.md

- en/api/configuration-global-name.md
- ja/api/configuration-global-name.md
- zh/api/configuration-global-name.md
Modify property `globalName`'s type from `Object` to `String`
> Fix globalName property type error

- en/api/context.md
Copied hidden information in the same file to be presented on the site docs.
Following the same style as https://github.com/nuxt/docs/blob/master/en/api/index.md
Looks to partially fix https://github.com/nuxt/docs/issues/932
---
I was trying to find where `this.$route` for example is defined in the documentation. I couldn't find it, and I know this doesn't fix that issue, hence suggesting this is a partial fix. I don't feel I'd know how to best explain this.
> Include information for context

- en/api/menu.json
- en/guide/configuration.md
The documentation for the dir configuration (https://github.com/nuxt/nuxt.js/pull/2748) existed but nothing linked to it. The modifications here include a link in the sidebar and a link and description in the Configuration page of the Guide.
Resolves #870
> en: link to dir configuration in Configuration page and API menu 

- en/faq/deployment-aws-s3-cloudfront.md
- Fix typo of CloudFront spelled CouldFront
- Case CloudFront consistently across readme according to business' casing of `CloudFront`
> Update deployment-aws-s3-cloudfront guide

- en/faq/host-port.md
Host `0.0.0.0` have different meanings between different contexts.
I added a clarification to what host `0.0.0.0` is designated to in this specific context.
> Add 0.0.0.0 usage clarification

- en/guide/assets.md
The original reference URL is not accessible, look like https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/base.js#L297-L316 is the right place.
> Update loader configuration reference in assets.md

- ja/guide/modules.md
Fix Markdown.
https://ja.nuxtjs.org/guide/modules#%E7%89%B9%E5%AE%9A%E3%81%AE%E3%83%95%E3%83%83%E3%82%AF%E3%81%A7%E3%82%BF%E3%82%B9%E3%82%AF%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B
> fix japanese modules markdown

- en/api/pages-scrolltotop.md
Previously linked to #scrollBehavior which was invalid.
> Fixed #scrollbehavior anchor link.

- ja/api/menu.json
@inouetakuya @potato4d 先日の PR（#1174）で今回翻訳対象外の項目を追加していたので、削除 PR です:bow:
> ja: Remove menu of $nuxt from ja/api/menu.json

- ja/faq/now-deployment.md
I translated now-deployment.md from en to ja for Now v2.
> ja: Translate now-deployment.md to ja

- ja/api/pages-loading.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/122 の翻訳しましたので、
確認お願いします 🙏 
差分ですが、新規になります。
```diff
diff --git a/en/api/pages-loading.md b/en/api/pages-loading.md
new file mode 100644
index 0000000..63cbb01
--- /dev/null
+++ b/en/api/pages-loading.md
@@ -0,0 +1,28 @@
+---
+title: "API: The loading Property"
+description: The `loading` property gives you the option to disable the default loading progress bar on a specific page.
+---
+
+# The loading Property
+
+> The loading property gives you the option to disable the default loading progress bar on a specific page.
+
+- **Type:** `Boolean` (default: `true`)
+
+By default, Nuxt.js uses its own component to show a progress bar between the routes.
+
+You can disable or customize it globally through the …
```
> ja: Translate api/pages-loading.md

- ja/faq/google-analytics.md
vuejs-jp#69 の差分の翻訳が完了しました。ソースコードのみの差分でした。
enの差分はこちらです。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-76303847b8263a974984b25370aaed5c
> ja: Translate faq/google-analytics.md

- en/api/configuration-env.md
Changed process.env.you_var to process.env.your_var
> Fixed a minor typo

- ja/api/configuration-render.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/101 の翻訳しましたので、
確認お願いします 🙏 
対応するenは、 https://github.com/vuejs-jp/ja.docs.nuxtjs/blob/e53272a68e3a4ac45373ec333b14009f45dbf29b/en/api/configuration-render.md になります。
https://github.com/nuxt/docs/pull/1215/commits/21201006fcf2ec72203adcb2f078f7d78969527e のコミットで https://vuejs-jp.slack.com/archives/C1P227P7V/p1552140090015800 の対応をこのページだけで行っています
> ja: Translate api/configuration-render.md

- en/guide/plugins.md
If you try to `import` and `Vue.use()` a plugin that exports an ES6 module, the build will fail throwing `Unexpected identifier`, `Unexpected token import` or similar error messages, and the traces wont give any useful information.
This happens because babel wont transpile modules inside `node_modules`, so the build process won't understand the code and will fail to build.
Since using vue plugins is a common practice and there are many that export ES6 modules,  I suggest adding advice on the matter to the docs to prevent new users from having this problem.
> Update plugins.md adding notes on ES6 plugins.

- ja/api/configuration-global-name.md
vuejs-jp#91 の差分の翻訳が完了しました。
enの差分はこちらです。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-c396a6219396b7678badf1b19ad3bb17
上記差分の英文の追加はすでに済んでいたため、日本語訳への修正のみ行っています。また型の表記に関しては、vuejs-jp#126 の方針に合わせています。
> ja: Translate api/configuration-global-name.md

- ja/api/pages-scrolltotop.md
vuejs-jp#123 の差分を翻訳しましたのでご確認お願します。
`en/api/pages-scrolltotop.md` の差分はこちらです。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-1abb9acd20b50ae9c339b3c6ecede8a8
> ja: Translate api/pages-scrolltotop

- ja/lang.json
vuejs-jp#53 の日本語訳です。レビューお願いします。
1点気になっているところとしては、 `sponsors.become` と `sponsors.become_partner` の部分で、ドキュメント側の末尾に `.` がハードコーディングされているので、日本語のドキュメントにも `.` が表示されてしまう点です。ただ、これはドキュメント側を修正しないといけない問題なので、いったん無視して翻訳のみを行いました。
> ja: Translate lang.json into japanese

- en/api/configuration-render.md
- ja/api/configuration-render.md
- remove `(or a falsy value)` because [falsy value will disable compressor option](https://github.com/nuxt/nuxt.js/blob/ef41e205e6787b784ab5907d99652b9d74891c6c/packages/server/src/server.js#L78-L86)
- tweak Japanese translation
> fix: describe about render.compressor

- api.js
- en/homepage/backers.md
- en/homepage/modes.md
- en/homepage/modes_server_side_rendering.md
- en/homepage/modes_single_page_app.md
- en/homepage/modes_statically_generated.md
- en/homepage/welcome.md
- en/homepage/welcome_figure.md
- en/homepage/why.md
- en/homepage/why_enjoyable.md
- en/homepage/why_modular.md
- en/homepage/why_performant.md
See first: [/nuxt/nuxtjs.org/issues/178](/nuxt/nuxtjs.org/issues/178)
Add `/homepage` and `/homepage/(lang)` api for rendering homepage with each language.
This pull request includes:
1. `/homepage` and `/homepage/(lang)` api for the nuxtjs.org homepage rendering
2. Fallback function for missing language contents
3. Imported homepage data to `en/homepage/*.md`
> Add homepage api for rendering homepage with each language

- ja/api/configuration-head.md
vuejs-jp#92 の差分を翻訳しましたのでご確認お願します。
en/api/configuration-head.md の差分はこちらです。
https://github.com/nuxt/docs/compare/b000302..e53272a#diff-421f31192304e75988dab0da181e7389
> ja: Translate /api/configuration-head.md

- ja/faq/jsx.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/64 を翻訳しましたので、ご確認お願いいたします 🙏 
最新の en はこちらです。
https://github.com/nuxt/docs/blob/master/en/faq/jsx.md
`git diff b000302bd83a2bef8c00979c98ab1c2d62f2dcb0..e53272a68e3a4ac45373ec333b14009f45dbf29b en/faq/jsx.md` したところ、以下の差分は既に翻訳済みだったので、それ以外の差分を翻訳したのが本PRです。
```
-<p class="Alert Alert--info">Aliasing `createElement` to `h` is a common convention you’ll see in the Vue ecosystem but is actually optional for JSX since it [automatically injects](https://github.com/vuejs/babel-plugin-transform-vue-jsx#h-auto-injection) `const h = this.$createElement` in any method and getter (not functions or arrow functions) declared in ES2015 syntax that has JSX so you can drop the (h) parameter.</p>
+<div class="Alert Alert--orange">
+ …
```
> ja: Translate faq/jsx.md

- ja/api/components-nuxt-child.md
- ja/examples/menu.json
- ja/examples/named-views.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/81 を翻訳しましたのでご確認お願いします 🙏 
最新の en はこちらです。
https://github.com/nuxt/docs/blob/master/en/api/components-nuxt-child.md
`git diff b000302bd83a2bef8c00979c98ab1c2d62f2dcb0..e53272a68e3a4ac45373ec333b14009f45dbf29b en/api/components-nuxt-child.md` したところ、
以下の差分は https://github.com/nuxt/docs/commit/3d0d9895088db39dd5ee4ac2ef6fdd028d7d999b で翻訳されていたので、それ以外の差分を翻訳したのが本PRです。
```
+`<nuxt-child/>` accepts `keep-alive` and `keep-alive-props`:
+
+```html
+<template>
+  <div>
+    <nuxt-child keep-alive :keep-alive-props="{ exclude: ['modal'] }" />
+  </div>
+</template>
+
+
+<div>
+  <keep-alive :exclude="['modal']">
+    <router-view />
+  </keep-alive>
+</div>
+```
```
> ja: Translate api/components-nuxt-child.md

- ja/api/components-nuxt-link.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/82
翻訳対象にあたる b000302..e53272a 間のDiffと翻訳時点のmaster(2d360beb)の内容に差分があったため、masterの内容（下記）を訳しています。
https://github.com/nuxt/docs/blob/2d360beb89988d415a711c7059cf95943f24e352/en/api/components-nuxt-link.md
よろしくお願いいたします。
> ja: Translate /api/components-nuxt-link.md

- ja/api/configuration-modern.md
https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/97 の翻訳をしましたので、確認お願いします 🙏 
https://github.com/nuxt/docs/pull/1174 にて翻訳対象の英語版が入っているので、PR上の差分で確認できます。
> ja: api/configuration-modern を翻訳

- en/api/internals-generator.md
`generate:routeCreated` signature in the docs is `route, path, errors` but in reality, it's `{route, path, errors}`
> Fix small issue with the generate:routeCreated signature.

- ja/guide/routing.md
I fixed a destination of link on the `routing/#ミドルウェア` page in Japanese since the destination wasn't correct.
Current destination(which leads to `/api/` ) :  https://ja.nuxtjs.org/api#%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88
Fixed destination:
https://ja.nuxtjs.org/api/context
「ミドルウェア」の項目で「コンテキスト」ページへの向き先が異なっていたので修正しました。
現在のリンク先( `/api/` に遷移します ): https://ja.nuxtjs.org/api#%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88
修正後のリンク先: 
https://ja.nuxtjs.org/api/context
> ja: Fix a destination of link on "routing/#ミドルウェア"

- en/guide/typescript.md
Contributes to fixing #1323. Specifically the missing interface keyword.
> docs(ts): fix missing `interface` keyword in snippet

- zh/guide/contribution-guide.md
* Update the open source contribution guide document to synchronize with the English document in 2.4.X version
> zh: Update the open source contribution guide document

- fr/guide/routing.md
I just translate a section that was missing in the French version of the help.
> fr: Adding missing "Unknown Dynamic Nested Routes" section

- en/faq/heroku-deployment.md
The previous command may raise an exceeded memory usage error in Heroku. 
"nuxt start" seems to be just fine.
> Procfile cmd no longer raises memory error

- en/faq/webpack-audio-files
I hard a hard time finding how to achieve this in Nuxt 2.
Please correct me if this is not the optimal way 🙇‍♂️
I tried setting `transformAssetUrls` in the extend function. It did update the config, but I still couldn't import audio file with the `src` attribute.
```js
export default {
build: {
extend (config, { isClient, loaders: { vue } }) {
// This doesn't work for me.
vue.transformAssetUrls.audio= 'src'
config.module.rules.push({
test: /\.(ogg|mp3|wav|mpe?g)$/i,
loader: 'file-loader',
options: {
name: '[path][name].[ext]',
},
})
}
}
}
```
> Add FAQ about loading audio files with Webpack

- ja/guide/typescript.md
resolve: [[doc] docs(ts): fix missing `interface` keyword in snippet · Issue #138 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/138)
> ja: docs(ts): fix missing `interface` keyword in snippet

- ja/lang.json
resolve: [[doc] chore(version): Set version to 2.5.X for english · Issue #128 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/128)
> ja: "docVersion": "2.6.X"

- zh/api/components-nuxt-link.md
- zh/api/configuration-dev.md
- zh/api/configuration-ignore.md
- zh/api/configuration-render.md
- zh/api/configuration-router.md
- zh/api/index.md
- zh/api/menu.json
- zh/api/pages-fetch.md
- zh/guide/async-data.md
- zh/guide/commands.md
- zh/guide/development-tools.md
- zh/guide/directory-structure.md
- zh/guide/index.md
- zh/guide/installation.md
- zh/guide/modules.md
- zh/guide/plugins.md
- zh/guide/routing.md
- zh/guide/typescript.md
- zh/guide/views.md
- zh/guide/vuex-store.md
- zh/lang.json
* API分类，`.nuxtignore`文档新增
* API分类，render模块: `fallback`新增，并增加目录索引：`ssr`, `static`, `dist`, 'csp'等
* API分类，router模块: `prefetchLinks`, `scrollBehavior`, `linkPrefetchedClass`等文档新增
* API分类， nuxt-link模块： `no-prefetch`等文档新增
* Guide分类， modules模块：模块列表，module package commands 等
* Guide分类， plugins模块：ES6插件
* Guide分类， typescript模块新增TS使用
* API分类，asyncData模块： 删除表格，重复
* 更新版本号为: 2.6.X版本
* Gui分类，Vuex中修正中文文档错误
------
* API, new to `.nuxtignore` document
* API, render module: `fallback` added, and add directory index: `ssr`, `static`, `dist`, 'csp', etc.
* API, router module: `prefetchLinks`, `scrollBehavior`, `linkPrefetchedClass`
* API, nuxt-link module: new documentation such as `no-prefetch`
* Guide, modules module: module list, module package commands
* Guide, plugins module: ES6 plugin
* Guide, …
> zh: Update Chinese documents to synchronize with English documents

- fr/guide/vuex-store.md
The information for the Classic mode is not the same as the English version (deprecated in Nuxt 3)
> fr: Update classic mode informations

- en/faq/appengine-deployment.md
The flag `--project` seems not to be supported [any more]. Run `gcloud help app deploy` for more details.
This change in the deployment command is tested on my personal project.
> Remove  --project <project-id>

- fr/api/components-nuxt-link.md
Fix two dead links for the French translation of the [`<nuxt-link>` page](https://fr.nuxtjs.org/api/components-nuxt-link/).
> fr: fix <router-link> docs URL

- configuration-build.md
https://webpack.js.org/guides/code-splitting-libraries/ is broken on filename entry: replace it with https://webpack.js.org/guides/code-splitting/
> Link to webpack code splitting is broken on filenames entry

- ja/api/pages-middleware.md
"Middleware Guide" is linked incorrectly. This pull request is for modifying it.
> Modify Middleware Link

- de/api/components-nuxt.md
- en/api/components-nuxt.md
- es/api/components-nuxt.md
- ja/api/components-nuxt.md
- ko/api/components-nuxt.md
Related: https://github.com/nuxt/nuxt.js/pull/5757
With the pull request above, `watchQuery` no more affects `nuxtChildKey`.
> doc: remove 'watchQuery' section from 'nuxtChildKey' doc

- en/guide/contribution-guide.md
Added a link directly to the nuxt repo as saying fork this repo is wrong as you are not in the repo you are on the docs website
> docs(contribution-guide): added link to nuxt repo

- en/api/pages-key.md
> fix a typo

- de/api/components-nuxt.md
- en/api/components-nuxt.md
- en/api/configuration-build.md
- en/api/configuration-render.md
- en/api/menu.json
- en/lang.json
- es/api/components-nuxt.md
- ja/api/components-nuxt.md
- ko/api/components-nuxt.md
Updates for https://github.com/nuxt/nuxt.js/pull/5765
> version: v2.8.0

- en/api/configuration-generate.md
Sometimes it's not obvious what the generate property is and how to modify it especially if you are not generating dynamic pages therefore don't have a generated property in your nuxt.config.js and one isn't there by default. Adding an example might make things a bit clearer especially for the subFolders option which I think is one that might be used a lot. We could of course add the example for each one to make it even clearer but explaining what other options you could have for example the fallback default is 200, what else would you put or are these things that nobody will change therefore we are just telling people that they are there. It would be great to have a better understanding of some of these generate features.
> docs: configuration-generate

- de/api/context.md
- en/api/context.md
- fr/api/context.md
- id/api/context.md
- pt-BR/api/context.md
some of the keywords in the section does not wrapped in back quotations correctly so that it shows like below; 'middleware', 'modules', and 'nuxtServerInit`.
This PR fixes it in some languages which have `api/context.md`.
> fix: use backquotation for the keywords in "API: The Context" chapter

- en/api/pages-transition.md
- change `transition` key to `pageTransition`
- added info from which version and when `transition` will be deprecated
- added subsection about transition mode
> Updated en-docs about page transitions

- en/guide/development-tools.md
Its no longer necessary define babel configs because conflicts with the Ava have by default, and cause some conflicts
In addition, if you write your tests inside a test folder, you need to define it in the package.json, ava object, with the `files` key
https://github.com/avajs/ava#latest-javascript-support
> en: Update development-tools.md

- ja/api/context.md
fix: [[doc] fix: use backquotation for the keywords · Issue #195 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/195)
> ja: fix: use backquotation for the keywords

- en/guide/upgrading.md
Hi, I recently had a [frustrating experience](https://github.com/nuxt/nuxt.js/issues/6079) trying to upgrade. While trying to upgrade to 2.8.1 I couldn't find clear instructions on how to upgrade. I eventually found the instructions on previous versions (2.6.0, 2.3.1), but it took a while to find them and once I did find them I wasn't confident they were still relevant to the version I wanted to upgrade to.
I imagine I'm not alone in wishing these instructions were featured more prominently in the documentation. I've taken the instructions from the 2.6.0 release and expanded upon them in order to make them more explicit. I can also see this being a section on the Installation page or the FAQ page.
Not sure if I'm following protocol for a submission so please let me know how I can help. …
> en: add upgrading instructions

- fr/guide/index.md
Vuex link redirected to `https://ssr.vuejs.org/fr` which is not the correct library
Vue Server Renderer link redirected to `https://ssr.vuejs.org/fr` which is a 404 page because `ssr.vuejs.org` doesn't have french translation yet
> fr: fix some links

- en/guide/views.md
Fixed line numbers in the URL and added a dot.
> Fix the link to vue-meta Nuxt.js example

- en/guide/index.md
The tag for the "Single Page Applications" heading was an h3, changed it to an h2.
> Made headings consistent

- en/guide/development-tools.md
Ava supports [test context](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#test-context), which can be used to pass Nuxt server instance. It's a better practice because you don't have to deal with scope variables declared here and there, and also your test functions become more pure and isolated.
> Promote using ava test context to pass nuxt

- de/lang.json
- es/lang.json
- id/lang.json
- ja/lang.json
- ko/lang.json
- pt-BR/lang.json
- ru/lang.json
- zh/lang.json
Related: https://github.com/nuxt/docs/commit/16228d9239e86da060c75679c541fa7404af11d0
close: [[doc] fix: rename backer to nuxter · Issue #227 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/227)
> fix: rename backer to nuxter

- ja/api/configuration-build.md
close: [[doc] docs(configuration-build): add yarn before command · Issue #231 · vuejs-jp/ja.docs.nuxtjs](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/231)
> ja: docs(configuration-build): add yarn before command

- en/api/configuration-servermiddleware.md
req.path is not found for the Node versions that I'm using... Perhaps there are some older Node versions that had `req.path`?
> Update path -> url

- en/guide/routing.md
Firebase Hosting now automatically supports `404.html` with a default 404 status code without having to modify `firebase.json` anymore. Using the previous config from these docs actually resulted in a response code of 200 for Page Not Found errors.
> en: update firebase custom 404.html handling

- en/api/components-client-only.md
Fixes a typo in the closing tag of `<client-only>`
> en: fix typo in components-client-only.md

- en/api/configuration-head.md
Many people adhere to a belief that you use the article “a” before words that begin with consonants and “an” before words that begin with vowels. But that isn’t the rule.
The real rule is this: You use the article “a” before words that start with a consonant sound and “an” before words that start with a vowel sound. For example, "He has a unique point of view on the subject and talked about it for an hour". The “u” in “unique” makes the “Y” sound—a consonant sound—therefore you use “a” as your article, while the “h” in “hour” sounds like it starts with “ow” — a vowel sound.
(c) Brian A. Klems, https://www.writersdigest.com/online-editor/a-before-consonants-and-an-before-vowels-is-not-the-rule
> en: fix typo

- en/guide/directory-structure.md
Update overlapping header h2 and h3 due to css `inline-block`
Live URL: https://nuxtjs.org/guide/directory-structure
- **Old**
- **New**
> Update heading alignment

- en/api/configuration-env.md
Based on this answer: https://github.com/nuxt/nuxt.js/issues/2800#issuecomment-414041637
(It took me quite some time to figure out why it wasn't working on my case; so I'm documenting what's the expected behavior.)
> Noting that serverMiddleware can't access nuxt env variables

- en/api/configuration-render.md
- ja/api/configuration-render.md
Just fixing a minor typo that can create confusion when typing this property (correctly) from memory.
Replacing all occurrences of `unsafeInlineCompatiblity` to `unsafeInlineCompatibility`.
Please watch: https://github.com/nuxt/nuxt.js/pull/6583
> Fixing a small typo on SSR CSP property name.

- en/api/pages-watchquery.md
Also, add an example using the function API.
This closes #1631
> Document that watchQuery can be a function

- en/api/configuration-build.md
I found `config.devtool = '#source-map'` does not work in Nuxt 2.10.
So I create a pull request to fix it.
This line worked well in nuxt 2.7. However, in Nuxt 2.10 it works not enough. Nuxt2.10 generates some invalid sourcemap files without error. I don't know that this problem depends on whether webpack or nuxt.
> Fix: sourcemap config

- ja/lang.json
Improve #1652
> Original message `"/" to focus` means **type "<kbd>/</kbd>" key to focus search input area**, 「絞り込み」has no meaning.
>
> _Originally posted by @hinaloe in https://github.com/nuxt/docs/pull/1652#issuecomment-545508020_
> ja: improve translate of focus

- de/faq/google-analytics.md
- en/faq/google-analytics.md
- es/faq/google-analytics.md
- fr/faq/google-analytics.md
- ja/faq/google-analytics.md
- ko/faq/google-analytics.md
- pt-BR/faq/google-analytics.md
- ru/faq/google-analytics.md
- zh/faq/google-analytics.md
I have updated to plugin configuration part from `ssr: false`, cause of deprecated, to `mode: 'client'`.
> [Docs] Update GA Plugin to `mode: 'client'`

- fr/guide/views.md
I'm not sure about this one but something should be done as the menu is using `Document` and the views.md section title related is `modèle de l'application` so the link does not work.
I don't think this term is really used in french and `Document` is simple enough.
> fr: update views.md first section title

- fr/guide/menu.json
Fix the root and context injection menu link to work with the section title.
> fr: fix menu.json link in plugins section

- en/guide/views.md
I think it makes more sense to link to the docs. I personally prefer to learn about through its nice docs website, instead of reading through the readme.md file.
> Link to vue-meta website instead of GitHub repo

- ja/faq/nginx-proxy.md
Added a semicolon at the end of document root in nginx-proxy.md :bow:
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/308
> ja: Add necessary semicolon in nginx-proxy.md

- fr/api/pages-head.md
The verb "utiliser" in the phrase "hid est utiliser" should be spelled "utilisé" like "hid est utilisé".
> Fixed french typo

- en/api/nuxt-render-route.md
Fixed a typo in the comments // `html` will be always a string to // `html` will always be a string
> Fixed typo in nuxt-render-route.md

- ko/api/configuration-loading.md
`~components/loading.vue` doesn't reference the given component properly.
Instead `~/components/loading.vue` worked. (Tested on Nuxt v2.10.2)
> Fix to reference loading component correctly

- en/guide/vuex-store.md
I have removed the word "simply" in two places. The first instance is plain incorrect: this document is far from complete. "Simply" exporting something (how, from where, synchronous, asynchronous, in the deprecated index.js?) does not work at all. And the second instance is plain unnecessary.
> Removed improper use of the adjective 'simply'

- en/faq/dokku-deployment.md
If the project uses Yarn (has a `yarn.lock` file) Dokku will need `YARN_PRODUCTION=false` as an environment variable to disable pruning of `devDependencies`.
> Added Dokku example config for Yarn users

- en/guide/commands.md
> en: document cli:buildError

- ja/guide/typescript.md
Changed the link to typescript.nuxtjs.org to Japanese directory
> ja: Fix link of guide/typescript.md

- en/api/pages-transition.md
I made it easier to understand how to use page-transition JS hooks. Please review the changes.
- Changed `pageTransition` to `transition`, making it consistent with this page.
- Added an example code for JS hooks.
Thank you!
> Update the JS hooks part in page-transition.md

- en/api/internals-renderer.md
> Minor grammar fix

- en/faq/heroku-deployment.md
According to [this](https://devcenter.heroku.com/changelog-items/1573)
> en: document delete heroku-deployment section

- ja/api/configuration-env.md
contextを使用したenvへのアクセス方法が間違っていたので修正しました。
> ja: Fix missing env

- en/api/configuration-ignore.md
As discussed on discord, we should remove the deprecation notice when these props will no longer be deprecated
> en: ignore(Prefix) properties will no longer be deprecated with nuxt v3

- ja/guide/routing.md
I translated `docs(middleware): Make it more clear that middleware key can accept an array of multiple middlewares` in #1809 to Japanese.
Please review 🙏 
resolve vuejs-jp#336
> ja: translate `docs(middleware): Make it more clear that middleware key can accept an array of multiple middlewares` to Japanese

- zh/api/configuration-loading.md
The introduction method here should be changed to '~ / components / loading.vue', otherwise an error not found will be reported
> A tiny mistake

- en/guide/commands.md
This flag is called `--fail-on-page-error` in docs, but in code it is actually `--fail-on-error`. That seems incorrect and confusing (at least to me).
See https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/commands/generate.js#L49
> en: fix name of flag to --fail-on-error

- README.md
@53able 
対応がめっちゃ遅くなって、ほんっと申し訳ありませんでした（なんか気絶してたのかなと笑っちゃうくらい）
下記を確認お願いします 🙏 
- 表示名
-  `53` にするのが良いのか `Go Tadano` が良いか迷いました（お好きなほうで）
- リンク先の URL
- とりあえず GitHub のアカウントページにしていますが、他の方のを見ると結構自由だったりするので「こっちを見てほしい」という URL があれば教えてください
> ja: Add 53able to Japanese primary maintainer(s)

- en/guide/index.md
Added a plural ('s) to `Nuxt's goal`
Added "in" to `you can plug in Nuxt.js`
> Fixed small grammatical errors in english guide

- ja/guide/commands.md
resolve https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/346
[コマンドのフラグ名差分](https://github.com/nuxt/docs/commit/a545eef904c4979417e53bfb6ef7666359d0fe7c)に対応しました。
レビューお願い致します🙇‍
> ja: Translate guide/commands.md

- en/api/menu.json
- en/api/pages-fetch.md
Related PR: https://github.com/nuxt/nuxt.js/pull/6880
> en: new fetch documentation

- en/blog/nuxtjs-from-terminal-to-browser.md
- en/blog/nuxtjs-v240-is-out-typescript-smart-prefetching-and-more.md
@Atinux just take a look at those two blog posts, missing description and imgUrl for `en/blog/nuxtjs-v240-is-out-typescript-smart-prefetching-and-more.md`
> feat(blog): add blog posts into en/blog directory

- en/faq/http-proxy.md
@nuxtjs/proxy is one of dependencies, not devDependencies because it is required at runtime.
see: https://github.com/nuxt-community/proxy-module#setup
> Remove -D option

- en/guide/directory-structure.md
can't -> can
I'm new to Nuxt.  While going through the documentation I encountered what I believe is a typo.  If I'm wrong and you **cannot** use `asyncData` or `fetch` then we should change `either` + `or` to `neither` + `nor` or remove `either entirely.
Thanks!
> Fix typo in description of Components Directory

- en/faq/pre-processors.md
Pug is now 2.0.4 released. And we have no reason to specify the Pug version anymore.
> en: don't pin pug dep

- en/faq/heroku-deployment.md
Hi, 
the NPM_CONFIG_PRODUCTION=false is outdated, and not necessary anymore:
>By default, Heroku will install all dependencies listed in package.json under dependencies and devDependencies.
>After running the installation and build steps Heroku will strip out the packages declared under devDependencies before deploying the application.
https://devcenter.heroku.com/articles/nodejs-support#package-installation
> en: remove useless section of heroku deployment.

- en/api/pages-fetch.md
`fetchOnServer` can be a function : https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/mixins/fetch.server.js#L35
> docs: fix fetchOnServer type

- en/faq/appengine-deployment.md
`NODE_ENV` is set to `production` by Google App Engine itself. No need to redefine it.
https://cloud.google.com/appengine/docs/standard/nodejs/runtime#environment_variables
> en: remove unnecessary env variable from GAE deploy

- fr/api/configuration-build.md
- fr/api/configuration-hooks.md
- fr/api/configuration-loading-indicator.md
- fr/api/configuration-mode.md
- fr/api/configuration-modern.md
- fr/api/configuration-modules.md
- fr/api/configuration-modulesdir.md
- fr/api/configuration-plugins.md
- fr/api/menu.json
- fr/api/pages-fetch.md
- fr/guide/menu.json
- fr/guide/modules.md
Translated pages: 
- fr/api/configuration-build.md 
- fr/api/configuration-hooks.md 
- fr/api/configuration-loading-indicator.md
- fr/api/configuration-mode.md 
- fr/api/configuration-modern.md 
- fr/api/configuration-modules.md
- fr/api/configuration-modulesdir.md 
- fr/api/configuration-plugins.md 
- fr/api/pages-fetch.md 
+ updated menu : 
- fr/api/menu.json
- fr/guide/menu.json
> fr: add translation for api (fetch + configuration)

- ja/api/configuration-router.md
I fixed an unbalanced quotation in `api/configuration-router.md`.
> ja: fix unbalanced quotations

- en/guide/directory-structure.md
New users who are not familiar with Nuxt's architecture need an easy jump off point in case they're wondering what this restriction is. The current verbiage:
> The components directory contains your Vue.js Components. You can't use asyncData in these components.
assumes knowledge of what asyncData is when it shows up later in the guide. In addition, this warning does give the user a reason to pause and doubt themselves as to whether they need to learn about asyncData before continuing with the guide. And this is a fairly dangerous rabbit hole if this knowledge is not essential to getting started.
Since this limitation was included in the original docs, I'm assuming that this was a common confusion point for users; therefore the better compromise might be to wrap it in the warning box as a …
> en: reduce confusion around asyncData

- en/guide/async-data.md
This blog post no longer available under Zeit/Vercel https://zeit.co/blog/async-and-await.
On visiting the link it takes to Vercel homepage
> en: remove gone blog post link

- en/blog/understanding-how-fetch-works-in-nuxt-2-12.md
Makes clear that we can use `this.$nuxt.error` inside `fetch`.
> en(blog): improve wording in fetch article

- en/guide/directory-structure.md
I think this should link to the `asyncData` page but is wrong and was closed with a `]` instead of a `)` accidentally.
> en(directory-structure): fix link to `asyncData`

- en/guide/routing.md
@manniL shared some useful information on https://github.com/nuxt/nuxt.js/issues/7472#event-3414840686.
Do you think this is a nice addition and understandable phrased?
> en: enhance routing-middleware docs

- en/api/configuration-generate.md
Changed less-than-equals ( <= ) sign with greater-than-equals sign ( >= )
Crawler is available by default from Nuxt v2.13 and greater.
> Fixed a typo in Crawler Key

- en/faq/github-pages.md
first `build` then `export` throws `Nuxt Fatal Error`:
Error: In order to use `nuxt export`, you need to run `nuxt build --target static`
> fix order of command line generate script

- en/api/pages-middleware.md
The previous link gave a 500 error. The new link is correct and tested.
> fixed typo in pages-middleware.md
